SHELL := bash
.SHELLFLAGS := -euxo pipefail -c
.ONESHELL:
.SILENT:
.DEFAULT_GOAL := help

# Tooling
TART_HOME ?= .tart
TART_HOME_FOREIGN ?= .tart.foreign
.tart.home ?= $(strip $(TART_HOME))
.tart.home.foreign ?= $(strip $(TART_HOME_FOREIGN))
.packer.cmd ?= packer
.tart.cmd ?= tart
.env.file ?= .env
-include $(.env.file)

TART_WORKING_VM ?= nikopol
TART_EXTRA_DISKS_ADD_RENAMED ?= 0
TART_EXTRA_DISKS_RENAMED_FROM_VM ?= nikopol

define .env.load
set -a
. "$(.env.file)"
TART_HOME="$(.tart.home)"
TART_HOME_FOREIGN="$(.tart.home.foreign)"
set +a
endef

define .env.file.content
# Generated by Make. Edit Make variables instead.
# Flox manifest owns TART_HOME and TART_HOME_FOREIGN.
TART_WORKING_VM=$(.tart.vm.name)
TART_EXTRA_DISKS_ADD_RENAMED=$(TART_EXTRA_DISKS_ADD_RENAMED)
TART_EXTRA_DISKS_RENAMED_FROM_VM=$(TART_EXTRA_DISKS_RENAMED_FROM_VM)
TART_ATTACH_FOREIGN_RENAMED=$(TART_ATTACH_FOREIGN_RENAMED)
endef

define .packer.run
$(call .env.load)
if [[ "$(.dry-run.packer.effective)" == "1" ]]; then
	echo "DRY-RUN[packer]: $(.packer.cmd) $(1)"
else
	packer_cmdline="$(strip $(1))"
	if [[ "$$packer_cmdline" == build* ]]; then
		packer_log="$(.tart.home)/vms/$(.tart.vm.name).packer.log"
		mkdir -p "$(.tart.home)/vms"
		set +e
		$(.packer.cmd) $(1) 2>&1 | tee "$$packer_log"
		packer_ec="$${PIPESTATUS[0]}"
		set -e
		exit "$$packer_ec"
	else
		$(.packer.cmd) $(1)
	fi
fi
endef

define .tart.run
$(call .env.load)
if [[ "$(.dry-run.tart.effective)" == "1" ]]; then
	echo "DRY-RUN[tart]: TART_HOME=\"$${TART_HOME}\" TART_HOME_FOREIGN=\"$${TART_HOME_FOREIGN}\" $(.tart.cmd) $(1)"
else
	$(.tart.cmd) $(1)
fi
endef

.tart.base.ref ?= ghcr.io/cirruslabs/macos-tahoe-vanilla:latest
.tart.clone.force ?= 0
.tart.disk.recreate ?= 0
.tart.disk.blank.fs ?= APFS

.tart.disk.cmd.ensure-parent = if [[ "$(.dry-run.disk.effective)" == "1" ]]; then : "DRY-RUN[disk]: mkdir -p $(dir $1)"; else mkdir -p "$(dir $1)"; fi
.tart.disk.cmd.prepare-image = if [[ "$(.dry-run.disk.effective)" == "1" ]]; then if [[ "$(.tart.disk.recreate)" == "1" && -f "$2" ]]; then : "DRY-RUN[disk]: would recreate $1 disk: $2"; fi; if [[ -f "$2" ]]; then : "DRY-RUN[disk]: would reuse existing $1 disk: $2"; else : "DRY-RUN[disk]: would create $1 disk: $2 ($3G, fs $(.tart.disk.blank.fs))"; fi; else if [[ "$(.tart.disk.recreate)" == "1" && -f "$2" ]]; then : "Recreating $1 disk: $2"; rm -f "$2"; fi; if [[ -f "$2" ]]; then : "Reusing existing $1 disk: $2"; else diskutil image create blank --format ASIF --size $3G --fs "$(.tart.disk.blank.fs)" --volumeName "$1" "$2"; fi; fi
.tart.disk.cmd.show-info = : "$1: $2"; ls -lh "$2" 2>/dev/null || true

# Split-friendly grouping convention (future include files):
# - mk/tooling.mk: .*.cmd, .*.env.*
# - mk/flags.mk:   .packer.flags.* and toggle helpers
# - mk/disks.mk:   .tart.disk.* defaults/paths
# - mk/targets.mk: help/validate/build/run and operational targets

# Build defaults
.template.grow ?= templates/vanilla-tahoe.pkr.hcl
.template.customize ?= templates/nxmatic-tahoe.pkr.hcl
.template ?= $(.template.customize)
.tart.vm.name ?= $(subst ~,+,$(subst :,+,$(strip $(TART_WORKING_VM))))
.tart.stage.name-prefix ?=
.tart.stage.name-prefix.effective := $(if $(strip $(.tart.stage.name-prefix)),$(strip $(.tart.stage.name-prefix))-,)
.tart.stage.use-dedicated-homes ?= 0
.tart.stage.tart-home-root ?= .tart.stage
.tart.stage.link-source-vm ?= 1
.tart.stage.cleanup.on-success ?= 1
.tart.stage.cleanup.keep-logs ?= 1
.tart.stage.cleanup.include-stage1 ?= 0
.tart.stage1.tart-home ?= $(if $(call opt-enabled,.tart.stage.use-dedicated-homes),$(.tart.stage.tart-home-root)/stage1,$(.tart.home))
.tart.stage2.tart-home ?= $(if $(call opt-enabled,.tart.stage.use-dedicated-homes),$(.tart.stage.tart-home-root)/stage2,$(.tart.home))
.tart.stage3.tart-home ?= $(if $(call opt-enabled,.tart.stage.use-dedicated-homes),$(.tart.stage.tart-home-root)/stage3,$(.tart.home))
.tart.stage4.tart-home ?= $(if $(call opt-enabled,.tart.stage.use-dedicated-homes),$(.tart.stage.tart-home-root)/stage4,$(.tart.home))
.tart.stage1-vm.name ?= $(.tart.stage.name-prefix.effective)big-vanilla-tahoe
.tart.stage2-vm.name ?= $(.tart.stage.name-prefix.effective)nix-store-tahoe
.tart.stage3-vm.name ?= $(.tart.stage.name-prefix.effective)nix-darwin-tahoe
.tart.stage4-vm.name ?= $(.tart.stage.name-prefix.effective)nxmatic-customized-tahoe
# Default cleanup set for rm* targets: all nxmatic stage artifacts + final VM.
# Intentionally excludes stage1 bootstrap artifact (.tart.stage1-vm.name / big-vanilla).
.tart.vm.names ?= $(.tart.stage2-vm.name) $(.tart.stage3-vm.name) $(.tart.stage4-vm.name) $(.tart.vm.name)
.tart.rm.vm.name ?= $(.tart.vm.name)
.tart.update.from-vm ?= $(.tart.vm.name)
.tart.update.to-vm ?= $(.tart.vm.name)-refresh
.tart.update.profile ?= nxmatic
.tart.update.relax-session-tweaks ?= true
.tart.update.tart-home ?= $(.tart.stage.tart-home-root)/refresh
.tart.update.link-role-disks ?= 1
.tart.update.link-source-vm ?= 1
.tart.update.source-vm-alias ?= source-vm
.tart.base.home ?= $(.tart.home)
.tart.base.link-source ?= 0
.tart.vm.path = $(.tart.home)/vms/$(.tart.vm.name)
.tart.stage1.vm.path = $(.tart.stage1.tart-home)/vms/$(.tart.stage1-vm.name)
.tart.stage2.vm.path = $(.tart.stage2.tart-home)/vms/$(.tart.stage2-vm.name)
.tart.stage3.vm.path = $(.tart.stage3.tart-home)/vms/$(.tart.stage3-vm.name)
.tart.stage4.vm.path = $(.tart.stage4.tart-home)/vms/$(.tart.stage4-vm.name)
.tart.stage1.vm.state := $(.tart.stage1.vm.path).state.yaml
.tart.stage2.vm.state := $(.tart.stage2.vm.path).state.yaml
.tart.stage3.vm.state := $(.tart.stage3.vm.path).state.yaml
.tart.stage4.vm.state := $(.tart.stage4.vm.path).state.yaml
.tart.final.vm.state := $(.tart.vm.path).state.yaml
.provision.profile ?= full

# Account identity defaults (Make-level knobs -> Packer vars -> script env)
.account.primary-name ?= nxmatic
.account.primary-full-name ?= Stephane Lacoin (aka nxmatic)
.account.primary-alias ?= nxmatic
.account.primary-password ?= nxmatic
.account.primary-expected-uid ?= 501
.account.secondary-name ?= super
.account.secondary-password ?= super
.account.system-admin-name ?= admin
.account.system-admin-password ?= admin
.auto-login.user ?= $(.account.secondary-name)
.data.home-user ?= $(.account.primary-name)
.bootstrap.ssh.user ?=
.bootstrap.ssh.password ?=

# Tart disk sizing defaults (GB)
.tart.disk.root.max-size-gb ?= 100
.tart.disk.root.format ?= raw
.tart.disk.user.max-size-gb ?= 160
.tart.disk.user-library.max-size-gb ?= 40
.tart.disk.git-bare-store.max-size-gb ?= 8
.tart.disk.git-store.max-size-gb ?= 9
.tart.disk.nix-store.max-size-gb ?= 180
.tart.disk.user-build-chains-cache.max-size-gb ?= 64
.tart.disk.vm-images.max-size-gb ?= 512

# Tart initial in-VM APFS sizes (GB)
.tart.disk.user.initial-size-gb ?= 64
.tart.disk.user-library.initial-size-gb ?= 20
.tart.disk.git-bare-store.initial-size-gb ?= 4
.tart.disk.git-store.initial-size-gb ?= 6
.tart.disk.nix-store.initial-size-gb ?= 90
.tart.disk.user-build-chains-cache.initial-size-gb ?= 16
.tart.disk.vm-images.initial-size-gb ?= 120

# Optional toggles
.enable-boot-command ?= false
.attach-data-disk-during-build ?= true
.interactive ?= 1
.debug ?= 1
.experimental ?= 0
.macos.enable-darwin-boot-args ?= true
.macos.darwin-boot-args ?= -v
.macos.relax-session-tweaks ?= true
.recovery.partition.mode ?= keep
.nix.store.volume-label ?= Nix Store
.nix.store.system-mount-point ?= /nix
.nix.store.configure-system-mount ?= true
.nix.store.configure-synthetic ?= true

# Hierarchical dry-run controls
# - Default is dry-run globally for safety.
# - Set .dry-run=0 (or scoped .dry-run.<scope>=0) to execute live operations.
# - Scoped vars (.dry-run.<scope>) when set take precedence over .dry-run.
.dry-run ?= 1
.dry-run.tart ?=
.dry-run.disk ?=
.dry-run.packer ?=
.dry-run.apfs.ownership ?=

.dry-run.tart.effective := $(if $(strip $(.dry-run.tart)),$(.dry-run.tart),$(.dry-run))
.dry-run.disk.effective := $(if $(strip $(.dry-run.disk)),$(.dry-run.disk),$(.dry-run))
.dry-run.packer.effective := $(if $(strip $(.dry-run.packer)),$(.dry-run.packer),$(.dry-run))
.dry-run.apfs.ownership.effective := $(if $(strip $(.dry-run.apfs.ownership)),$(.dry-run.apfs.ownership),$(.dry-run))

# Tart run profile defaults (for interactive/recovery troubleshooting)
.tart.run.vnc ?= 1
.tart.run.recovery ?= 0
.tart.run.net-bridged ?= Wi-Fi
.tart.run.root-disk-opts ?=
.tart.run.disk.opts ?= sync=full
.tart.run.extra-disks ?=
.tart.run.extra-disks.from-vm ?=
.tart.run.extra-disks.allow-duplicate-roles ?= 0
.tart.run.attach-foreign-renamed ?= $(if $(strip $(TART_ATTACH_FOREIGN_RENAMED)),$(TART_ATTACH_FOREIGN_RENAMED),0)
.tart.run.extra-disks.add-renamed ?= $(TART_EXTRA_DISKS_ADD_RENAMED)
.tart.run.extra-disks.renamed.from-vm ?= $(if $(strip $(TART_EXTRA_DISKS_RENAMED_FROM_VM)),$(TART_EXTRA_DISKS_RENAMED_FROM_VM),$(.tart.vm.name))
.tart.run.extra-disk.opts ?= sync=none
.tart.run.extra-args ?=
.tart.run.script.path ?= $(.tart.home)/vms/$(.tart.vm.name).sh
.tart.run.script.console ?= 1
.hotfix.control.root ?= hotfix/runtime
.hotfix.stage ?= $(.provision.profile)
.hotfix.stage.effective := $(if $(strip $(.hotfix.stage)),$(strip $(.hotfix.stage)),unknown)
.rm.skip-owned-disks-when-add-renamed ?= 1

.tart.run.extra-disks.add-renamed.effective = $(if $(filter true 1 yes on,$(strip $(.tart.run.attach-foreign-renamed))),1,$(.tart.run.extra-disks.add-renamed))
.tart.run.extra-disks.renamed.from-vm.effective = $(.tart.run.extra-disks.renamed.from-vm)
.tart.run.extra-disks.allow-duplicate-roles.effective = $(if $(filter true 1 yes on,$(strip $(.tart.run.attach-foreign-renamed))),1,$(.tart.run.extra-disks.allow-duplicate-roles))

# Foreign/local rename source selection
.tart.disk.rename.home ?= $(.tart.home.foreign)

# Host-side ASIF volume rename controls
.tart.disk.path ?=
.tart.disk.path.rename ?=
.tart.disk.name ?=
.tart.disk.base-dev ?=
.tart.disk.volume-dev ?=
.tart.disk.volume-devs ?=

# Role-disk source and prefix policy (migration-friendly)
.tart.disk.source-vm ?= $(.tart.vm.name)
.tart.disk.prefix.owner ?= $(.tart.disk.source-vm)
.tart.disk.prefix.enforce ?= $(if $(filter $(.tart.disk.source-vm),$(.tart.vm.name)),0,1)

# APFS ownership policy controls (cross-host disk access)
.apfs.ownership.script ?= bin/apfs-ownership-policy.sh
.apfs.ownership.mode ?= disable
.apfs.ownership.all-roles ?= 0
.apfs.ownership.include-system-mounts ?= 0
.apfs.ownership.images ?=

# Optional flag helper:
# enabled when variable is defined and not one of: false 0 no off (case-sensitive)
define opt-enabled
$(if $(filter undefined,$(origin $(1))),,$(if $(filter false 0 no off,$(strip $($(1)))),,1))
endef

define to-bool
$(if $(filter true 1 yes on,$(strip $(1))),true,false)
endef

ifneq ($(call opt-enabled,.interactive),)
.packer.flags.interactive := -debug
else
.packer.flags.interactive :=
endif

ifneq ($(call opt-enabled,.debug),)
ifneq ($(call opt-enabled,.interactive),)
.packer.flags.failure := -on-error=ask
else
.packer.flags.failure := -on-error=abort
endif
else
.packer.flags.failure :=
endif

# Computed default disk paths (align with template defaults)
.tart.disk.user.image-path ?=
.tart.disk.user-library.image-path ?=
.tart.disk.git-bare-store.image-path ?=
.tart.disk.git-store.image-path ?=
.tart.disk.nix-store.image-path ?=
.tart.disk.user-build-chains-cache.image-path ?=
.tart.disk.vm-images.image-path ?=

.tart.disk.user.image-path.effective = $(if $(strip $(.tart.disk.user.image-path)),$(.tart.disk.user.image-path),$(.tart.home)/disks/$(.tart.disk.source-vm)/user-data.asif)
.tart.disk.user-library.image-path.effective = $(if $(strip $(.tart.disk.user-library.image-path)),$(.tart.disk.user-library.image-path),$(.tart.home)/disks/$(.tart.disk.source-vm)/user-library.asif)
.tart.disk.git-bare-store.image-path.effective = $(if $(strip $(.tart.disk.git-bare-store.image-path)),$(.tart.disk.git-bare-store.image-path),$(.tart.home)/disks/$(.tart.disk.source-vm)/git-bare-store.asif)
.tart.disk.git-store.image-path.effective = $(if $(strip $(.tart.disk.git-store.image-path)),$(.tart.disk.git-store.image-path),$(.tart.home)/disks/$(.tart.disk.source-vm)/git-store.asif)
.tart.disk.nix-store.image-path.effective = $(if $(strip $(.tart.disk.nix-store.image-path)),$(.tart.disk.nix-store.image-path),$(.tart.home)/disks/$(.tart.disk.source-vm)/nix-store.asif)
.tart.disk.user-build-chains-cache.image-path.effective = $(if $(strip $(.tart.disk.user-build-chains-cache.image-path)),$(.tart.disk.user-build-chains-cache.image-path),$(.tart.home)/disks/$(.tart.disk.source-vm)/build-chains-cache.asif)
.tart.disk.vm-images.image-path.effective = $(if $(strip $(.tart.disk.vm-images.image-path)),$(.tart.disk.vm-images.image-path),$(.tart.home)/disks/$(.tart.disk.source-vm)/vm-images.asif)

.tart.disk.role.paths.effective = $(strip \
	$(.tart.disk.user.image-path.effective) \
	$(.tart.disk.user-library.image-path.effective) \
	$(.tart.disk.git-bare-store.image-path.effective) \
	$(.tart.disk.git-store.image-path.effective) \
	$(.tart.disk.nix-store.image-path.effective) \
	$(.tart.disk.user-build-chains-cache.image-path.effective) \
	$(.tart.disk.vm-images.image-path.effective))

.tart.run.disk.opts.suffix := $(if $(strip $(.tart.run.disk.opts)),:$(strip $(.tart.run.disk.opts)),)
.tart.run.extra-disk.opts.suffix := $(if $(strip $(.tart.run.extra-disk.opts)),:$(strip $(.tart.run.extra-disk.opts)),)
.tart.run.extra-disks.from-vm.dir := $(if $(strip $(.tart.run.extra-disks.from-vm)),$(.tart.home)/disks/$(.tart.run.extra-disks.from-vm),)
.tart.run.extra-disks.from-vm.paths := $(sort $(wildcard $(.tart.run.extra-disks.from-vm.dir)/*.asif))
.tart.run.role-disk.basenames := \
$(notdir $(.tart.disk.user.image-path.effective)) \
$(notdir $(.tart.disk.user-library.image-path.effective)) \
$(notdir $(.tart.disk.git-bare-store.image-path.effective)) \
$(notdir $(.tart.disk.git-store.image-path.effective)) \
$(notdir $(.tart.disk.nix-store.image-path.effective)) \
$(notdir $(.tart.disk.user-build-chains-cache.image-path.effective)) \
$(notdir $(.tart.disk.vm-images.image-path.effective))
.tart.run.extra-disks.from-vm.paths.filtered := $(foreach d,$(.tart.run.extra-disks.from-vm.paths),$(if $(filter $(notdir $(d)),$(.tart.run.role-disk.basenames)),,$(d)))
.tart.run.extra-disks.from-vm.paths.effective := $(if $(call opt-enabled,.tart.run.extra-disks.allow-duplicate-roles),$(.tart.run.extra-disks.from-vm.paths),$(.tart.run.extra-disks.from-vm.paths.filtered))
.tart.run.extra-disks.effective := $(strip $(.tart.run.extra-disks))

.tart.vm.name.paths := $(sort $(wildcard $(.tart.disk.rename.home)/disks/$(.tart.vm.name)/*.asif))
.tart.vm.name.paths.relative := $(patsubst $(CURDIR)/%,%,$(.tart.vm.name.paths))
.tart.vm.name.paths.rename-targets := $(addsuffix ~rename,$(.tart.vm.name.paths.relative))
.tart.vm.names.rm-runtime-targets := $(addsuffix ~rm-runtime,$(.tart.vm.names))
.tart.vm.names.rm-role-disks-targets := $(addsuffix ~rm-role-disks,$(.tart.vm.names))
.tart.disk.path.effective := $(if $(strip $(.tart.disk.path.rename)),$(.tart.disk.path.rename),$(.tart.disk.path))
.tart.disk.name.effective := $(if $(strip $(.tart.disk.name)),$(.tart.disk.name),$(if $(strip $(.tart.vm.name)),$(.tart.vm.name) - ,$(.tart.vm.name) - ))
.tart.disk.volume-devs.normalized := $(foreach d,$(strip $(.tart.disk.volume-devs)),$(patsubst /dev/%,%,$(d)))
.tart.disk.volume-devs.rename-targets := $(addsuffix ~rename-volume,$(.tart.disk.volume-devs.normalized))

define .packer.vars.full
-var vm_name=$(.tart.vm.name)
-var vm_base_name=$(.tart.base.ref)
-var tart_home=$(.tart.home)
-var provision_profile=$(.provision.profile)
-var enable_build_console=$(call to-bool,$(.interactive))
-var macos_primary_account_name=$(.account.primary-name)
-var 'macos_primary_account_full_name=$(.account.primary-full-name)'
-var macos_primary_account_alias=$(.account.primary-alias)
-var 'macos_primary_account_password=$(.account.primary-password)'
-var macos_primary_account_expected_uid=$(.account.primary-expected-uid)
-var macos_secondary_admin_name=$(.account.secondary-name)
-var 'macos_secondary_admin_password=$(.account.secondary-password)'
-var macos_system_admin_name=$(.account.system-admin-name)
-var 'macos_system_admin_password=$(.account.system-admin-password)'
-var macos_debug_mode=$(call to-bool,$(.debug))
-var macos_relax_session_tweaks=$(call to-bool,$(.macos.relax-session-tweaks))
-var macos_auto_login_user=$(.auto-login.user)
-var macos_bootstrap_ssh_username=$(.bootstrap.ssh.user)
-var macos_bootstrap_ssh_password=$(.bootstrap.ssh.password)
-var macos_data_home_user=$(.data.home-user)
-var 'macos_nix_store_volume_label=$(.nix.store.volume-label)'
-var 'macos_nix_store_system_mount_point=$(.nix.store.system-mount-point)'
-var macos_nix_store_configure_system_mount=$(call to-bool,$(.nix.store.configure-system-mount))
-var macos_nix_store_configure_synthetic=$(call to-bool,$(.nix.store.configure-synthetic))
-var macos_enable_darwin_boot_args=$(.macos.enable-darwin-boot-args)
-var 'macos_darwin_boot_args=$(.macos.darwin-boot-args)'
-var recovery_partition_mode=$(.recovery.partition.mode)
-var root_disk_format=$(.tart.disk.root.format)
-var root_disk_size_gb=$(.tart.disk.root.max-size-gb)
-var user_data_disk_initial_size_gb=$(.tart.disk.user.initial-size-gb)
-var user_library_disk_initial_size_gb=$(.tart.disk.user-library.initial-size-gb)
-var git_bare_store_disk_initial_size_gb=$(.tart.disk.git-bare-store.initial-size-gb)
-var git_store_disk_initial_size_gb=$(.tart.disk.git-store.initial-size-gb)
-var nix_store_disk_initial_size_gb=$(.tart.disk.nix-store.initial-size-gb)
-var user_build_chains_cache_disk_initial_size_gb=$(.tart.disk.user-build-chains-cache.initial-size-gb)
-var user_vm_images_disk_initial_size_gb=$(.tart.disk.vm-images.initial-size-gb)
-var user_data_disk_max_size_gb=$(.tart.disk.user.max-size-gb)
-var user_library_disk_max_size_gb=$(.tart.disk.user-library.max-size-gb)
-var git_bare_store_disk_max_size_gb=$(.tart.disk.git-bare-store.max-size-gb)
-var git_store_disk_max_size_gb=$(.tart.disk.git-store.max-size-gb)
-var nix_store_disk_max_size_gb=$(.tart.disk.nix-store.max-size-gb)
-var user_build_chains_cache_disk_max_size_gb=$(.tart.disk.user-build-chains-cache.max-size-gb)
-var user_vm_images_disk_max_size_gb=$(.tart.disk.vm-images.max-size-gb)
-var enable_boot_command=$(.enable-boot-command)
-var enable_vnc_url_probe=$(call to-bool,$(.interactive))
-var attach_data_disk_during_build=$(call to-bool,$(.attach-data-disk-during-build))
-var user_data_disk_image_path=$(.tart.disk.user.image-path.effective)
-var user_library_disk_image_path=$(.tart.disk.user-library.image-path.effective)
-var git_bare_store_disk_image_path=$(.tart.disk.git-bare-store.image-path.effective)
-var git_store_disk_image_path=$(.tart.disk.git-store.image-path.effective)
-var nix_store_disk_image_path=$(.tart.disk.nix-store.image-path.effective)
-var user_build_chains_cache_disk_image_path=$(.tart.disk.user-build-chains-cache.image-path.effective)
-var user_vm_images_disk_image_path=$(.tart.disk.vm-images.image-path.effective)
endef

define .packer.vars.grow
-var vm_name=$(.tart.vm.name)
-var vm_base_name=$(.tart.base.ref)
-var tart_home=$(.tart.home)
-var enable_build_console=$(call to-bool,$(.interactive))
-var recovery_partition_mode=$(.recovery.partition.mode)
-var root_disk_format=$(.tart.disk.root.format)
-var root_disk_size_gb=$(.tart.disk.root.max-size-gb)
-var enable_boot_command=$(.enable-boot-command)
-var enable_vnc_url_probe=$(call to-bool,$(.interactive))
-var macos_secondary_admin_name=$(.account.secondary-name)
-var 'macos_secondary_admin_password=$(.account.secondary-password)'
-var macos_system_admin_name=$(.account.system-admin-name)
-var 'macos_system_admin_password=$(.account.system-admin-password)'
-var macos_bootstrap_ssh_username=$(.bootstrap.ssh.user)
-var macos_bootstrap_ssh_password=$(.bootstrap.ssh.password)
endef

define .packer.vars.active
$(strip $(if $(strip $(.packer.vars.override)),$(.packer.vars.override),$(.packer.vars.full)))
endef

define .tart.run.disk.args
--disk="$(.tart.disk.user.image-path.effective)$(.tart.run.disk.opts.suffix)"
--disk="$(.tart.disk.user-library.image-path.effective)$(.tart.run.disk.opts.suffix)"
--disk="$(.tart.disk.git-bare-store.image-path.effective)$(.tart.run.disk.opts.suffix)"
--disk="$(.tart.disk.git-store.image-path.effective)$(.tart.run.disk.opts.suffix)"
--disk="$(.tart.disk.nix-store.image-path.effective)$(.tart.run.disk.opts.suffix)"
--disk="$(.tart.disk.user-build-chains-cache.image-path.effective)$(.tart.run.disk.opts.suffix)"
--disk="$(.tart.disk.vm-images.image-path.effective)$(.tart.run.disk.opts.suffix)"
endef

define .tart.run.extra.disk.args
$(foreach d,$(.tart.run.extra-disks.effective),--disk="$(d)$(.tart.run.extra-disk.opts.suffix)")
endef

define .tart.run.extra.disk.args.from-vm.shell
extra_from_vm_args=()
auto_renamed_mode=0
from_vm_name="$(strip $(.tart.run.extra-disks.from-vm))"
if [[ -z "$${from_vm_name}" && "$(.tart.run.extra-disks.add-renamed.effective)" == "1" ]]; then
	from_vm_name="$(strip $(.tart.run.extra-disks.renamed.from-vm.effective))"
	auto_renamed_mode=1
fi
if [[ -n "$${from_vm_name}" ]]; then
	from_vm_local_dir="$(.tart.home)/disks/$${from_vm_name}"
	from_vm_foreign_dir="$(.tart.home.foreign)/disks/$${from_vm_name}"
	scan_dir=""
	scan_pattern="*.asif"
	if [[ "$$auto_renamed_mode" == "1" ]]; then
		scan_pattern="$${from_vm_name} - *.asif"
		if [[ -d "$${from_vm_foreign_dir}" ]]; then
			scan_dir="$${from_vm_foreign_dir}"
		elif [[ -d "$${from_vm_local_dir}" ]]; then
			scan_dir="$${from_vm_local_dir}"
		else
			fallback_foreign_dir="$(.tart.home.foreign)/disks/$(.tart.vm.name)"
			fallback_local_dir="$(.tart.home)/disks/$(.tart.vm.name)"
			if [[ -d "$${fallback_foreign_dir}" ]]; then
				scan_dir="$${fallback_foreign_dir}"
			elif [[ -d "$${fallback_local_dir}" ]]; then
				scan_dir="$${fallback_local_dir}"
			fi
		fi
	else
		if [[ -d "$${from_vm_local_dir}" ]]; then
			scan_dir="$${from_vm_local_dir}"
		elif [[ -d "$${from_vm_foreign_dir}" ]]; then
			scan_dir="$${from_vm_foreign_dir}"
		fi
	fi
	if [[ -n "$${scan_dir}" ]]; then
		while IFS= read -r -d '' img; do
			base="$${img##*/}"
			normalized_base="$$base"
			from_vm_prefix="$${from_vm_name} - "
			if [[ "$$normalized_base" == "$${from_vm_prefix}"* ]]; then
				normalized_base="$${normalized_base#"$${from_vm_prefix}"}"
			elif [[ "$$auto_renamed_mode" == "1" ]]; then
				continue
			fi

			is_role_duplicate=0
			if [[ "$(.tart.run.extra-disks.allow-duplicate-roles.effective)" != "1" ]]; then
				for role_base in $(.tart.run.role-disk.basenames); do
					if [[ "$$normalized_base" == "$$role_base" ]]; then
						is_role_duplicate=1
						break
					fi
				done
			fi

			if [[ "$$is_role_duplicate" == "1" ]]; then
				continue
			fi

			extra_from_vm_args+=(--disk="$${img}$(.tart.run.extra-disk.opts.suffix)")
		done < <(find "$${scan_dir}" -maxdepth 1 -type f -name "$${scan_pattern}" -print0 | LC_ALL=C sort -z)
		if [[ "$$auto_renamed_mode" == "1" && "$${#extra_from_vm_args[@]}" -eq 0 ]]; then
			echo "Info: renamed-disk mode enabled, but no disks matched '$${scan_pattern}' in '$${scan_dir}'."
			echo "      Rename foreign disks as '<vm> - <role>.asif' to attach them in this mode."
		fi
	fi
fi
endef

define .tart.run.console.args
$(if $(call opt-enabled,.tart.run.vnc),$(if $(call opt-enabled,.experimental),--vnc-experimental,--vnc),)
$(if $(call opt-enabled,.tart.run.recovery),--recovery,)
$(if $(strip $(.tart.run.net-bridged)),--net-bridged="$(.tart.run.net-bridged)",)
$(if $(strip $(.tart.run.root-disk-opts)),--root-disk-opts="$(.tart.run.root-disk-opts)",)
endef

define .tart.run.script.args
$(strip $(if $(call opt-enabled,.tart.run.script.console),$(.tart.run.console.args),) $(.tart.run.disk.args) $(.tart.run.extra.disk.args) $(.tart.run.extra-args))
endef

define .tart.disk.cmd.rename-volume
echo "=== rename-disk-volume: $$image_path ==="
if [[ -z "$$image_path" ]]; then
	echo "Missing required disk image path" >&2
	exit 2
fi
if [[ ! -f "$$image_path" ]]; then
	echo "Image not found: $$image_path" >&2
	exit 2
fi
attached_by_script=0
base_dev="$(strip $(.tart.disk.base-dev))"
volume_dev_candidates="$(strip $(.tart.disk.volume-dev))"
container_dev=""
detach_targets=""
cleanup_done=0
cleanup_attached() {
	detach_dev() {
		local dev="$$1"
		local tries=0
		[[ -z "$$dev" ]] && return
		dev="$${dev#/dev/}"
		dev="/dev/$$dev"
		while [[ "$$tries" -lt 3 ]]; do
			diskutil unmountDisk force "$$dev" >/dev/null 2>&1 || true
			diskutil detach "$$dev" >/dev/null 2>&1 || hdiutil detach -force "$$dev" >/dev/null 2>&1 || true
			if ! diskutil info "$$dev" >/dev/null 2>&1; then
				return
			fi
			tries=$$((tries+1))
			sleep 1
		done
	}

	if [[ "$$cleanup_done" == "1" ]]; then
		return
	fi
	cleanup_done=1
	if [[ "$$attached_by_script" != "1" ]]; then
		return
	fi
	if [[ -n "$$detach_targets" ]]; then
		while IFS= read -r dev; do
			[[ -z "$$dev" ]] && continue
			detach_dev "$$dev"
		done <<< "$$detach_targets"
		return
	fi
	if [[ -n "$$base_dev" ]]; then
		detach_dev "$$base_dev"
	fi
}
if [[ -n "$$base_dev" ]]; then
	base_dev="$${base_dev#/dev/}"
	base_dev="/dev/$$base_dev"
fi
if [[ -n "$$volume_dev_candidates" ]]; then
	volume_dev_candidates="$${volume_dev_candidates#/dev/}"
	volume_dev_candidates="/dev/$$volume_dev_candidates"
fi
if [[ -z "$$volume_dev_candidates" ]]; then
	attached_by_script=1
	json=""
	attach_err=""
	for attach_try in 1 2 3; do
		set +e
		attach_plist="$$(diskutil image attach -nomount -nobrowse -plist "$$image_path" 2>&1)"
		attach_ec=$$?
		set -e
		if [[ "$$attach_ec" -eq 0 ]]; then
			json="$$(printf '%s\n' "$$attach_plist" | plutil -convert json -o - -- - 2>/dev/null || true)"
			if [[ -n "$$json" ]]; then
				attach_err=""
				break
			fi
			attach_err="diskutil attach returned unparsable plist output"
		else
			attach_err="$$attach_plist"
		fi
		if [[ "$$attach_try" -lt 3 ]]; then
			echo "Attach attempt $$attach_try failed for $$image_path; retrying..." >&2
			sleep 1
		fi
	done
	if [[ -z "$$json" ]]; then
		if printf '%s\n' "$$attach_err" | grep -Eiq 'resource temporarily unavailable|device busy|resource busy'; then
			echo "Skipping rename for in-use image: $$image_path" >&2
			echo "Hint: stop VMs using this disk, then rerun rename target for full coverage." >&2
			exit 0
		fi
		echo "Failed to attach image for rename: $$image_path" >&2
		if [[ -n "$$attach_err" ]]; then
			echo "Attach error: $$attach_err" >&2
		fi
		exit 1
	fi
	base_dev_raw="$$(printf '%s\n' "$$json" | yq -p json -r '."system-entities"[] | select(has("dev-entry")) | ."dev-entry" | select(test("^(/dev/)?disk[0-9]+$$"))')"
	base_dev_raw="$${base_dev_raw%%$$'\n'*}"
	detach_targets="$$(printf '%s\n' "$$json" | yq -p json -r '."system-entities"[] | select(has("dev-entry")) | ."dev-entry" | select(test("^(/dev/)?disk[0-9]+$$"))' | sed -E 's#^/dev/##' | awk '!seen[$$0]++ { print "/dev/" $$0 }')"
	container_dev_raw="$$(printf '%s\n' "$$json" | yq -p json -r '."system-entities"[] | select(has("dev-entry")) | select(."content-hint" == "Apple_APFS_Container") | ."dev-entry" | select(test("^(/dev/)?disk[0-9]+$$"))')"
	container_dev_raw="$${container_dev_raw%%$$'\n'*}"
	trap cleanup_attached EXIT
	volume_dev_candidates="$$(printf '%s\n' "$$json" | yq -p json -r '."system-entities"[] | select(has("dev-entry")) | select((."filesystem-type" == "apfs") or (."content-hint" == "Apple_APFS_Volume")) | ."dev-entry" | select(test("^(/dev/)?disk[0-9]+s[0-9]+$$"))')"
	if [[ -z "$$volume_dev_candidates" ]]; then
		volume_dev_candidates="$$(printf '%s\n' "$$json" | yq -p json -r '."system-entities"[] | select(has("dev-entry")) | select(."mount-point" != null) | ."dev-entry" | select(test("^(/dev/)?disk[0-9]+s[0-9]+$$"))')"
	fi
	if [[ -z "$$volume_dev_candidates" ]]; then
		volume_dev_candidates="$$(printf '%s\n' "$$json" | yq -p json -r '."system-entities"[] | select(has("dev-entry")) | ."dev-entry" | select(test("^(/dev/)?disk[0-9]+s[0-9]+$$"))')"
	fi
	if [[ -z "$$volume_dev_candidates" && -n "$$base_dev" ]]; then
		apfs_json="$$(diskutil apfs list -plist "$$base_dev" 2>/dev/null | plutil -convert json -o - -- - 2>/dev/null || true)"
		if [[ -n "$$apfs_json" ]]; then
			volume_dev_candidates="$$(printf '%s\n' "$$apfs_json" | yq -p json -r '.Containers[]? | .Volumes[]? | .DeviceIdentifier // empty' | sed -E 's#^/dev/##' | awk 'NF && !seen[$$0]++ { print }')"
		fi
	fi
	volume_dev_candidates="$$(printf '%s\n' "$$volume_dev_candidates" | awk '!seen[$$0]++')"
fi
if [[ "$$attached_by_script" == "1" && -n "$$base_dev_raw" ]]; then
	base_dev="$${base_dev_raw#/dev/}"
	base_dev="/dev/$$base_dev"
fi
if [[ "$$attached_by_script" == "1" && -n "$$container_dev_raw" ]]; then
	container_dev="$${container_dev_raw#/dev/}"
	container_dev="/dev/$$container_dev"
fi
if [[ -z "$$volume_dev_candidates" ]]; then
	echo "Failed to resolve attached APFS volume for $$image_path" >&2
	cleanup_attached
	exit 1
fi
if [[ "$$attached_by_script" == "1" && -z "$$base_dev" ]]; then
	echo "Failed to resolve attached APFS volume for $$image_path" >&2
	cleanup_attached
	exit 1
fi
# Expand raw APFS container slices (e.g. diskXs1 with empty VolumeName)
# into concrete APFS volume devices from their container reference.
expanded_volume_dev_candidates=""
while IFS= read -r raw_candidate; do
	[[ -z "$$raw_candidate" ]] && continue
	raw_candidate_dev="$${raw_candidate#/dev/}"
	raw_candidate_dev="/dev/$$raw_candidate_dev"
	raw_candidate_info_json="$$(diskutil info -plist "$$raw_candidate_dev" | plutil -convert json -o - -- - 2>/dev/null || true)"
	raw_candidate_name="$$(printf '%s\n' "$$raw_candidate_info_json" | yq -p json -r '.VolumeName // empty' 2>/dev/null || true)"
	raw_candidate_container="$$(printf '%s\n' "$$raw_candidate_info_json" | yq -p json -r '.APFSContainerReference // empty' 2>/dev/null || true)"
	if [[ -z "$$raw_candidate_name" && -n "$$raw_candidate_container" ]]; then
		container_apfs_json="$$(diskutil apfs list -plist "/dev/$$raw_candidate_container" 2>/dev/null | plutil -convert json -o - -- - 2>/dev/null || true)"
		container_volume_devs="$$(printf '%s\n' "$$container_apfs_json" | yq -p json -r '.Containers[]?.Volumes[]?.DeviceIdentifier // empty' 2>/dev/null || true)"
		if [[ -n "$$container_volume_devs" ]]; then
			expanded_volume_dev_candidates+="$$container_volume_devs"$$'\n'
			continue
		fi
	fi
	expanded_volume_dev_candidates+="$${raw_candidate_dev#/dev/}"$$'\n'
done <<< "$$volume_dev_candidates"
volume_dev_candidates="$$(printf '%s\n' "$$expanded_volume_dev_candidates" | awk 'NF && !seen[$$0]++ { print }')"

mounted_for_rename=0
rename_mount_dir=""
volume_dev=""
old_name=""
encrypted_or_locked_detected=0
container_mount_attempted=0
saw_prefixed_volume=0
rename_dry_run="$(.dry-run.disk.effective)"
if [[ -z "$$rename_dry_run" ]]; then rename_dry_run=0; fi
while IFS= read -r candidate; do
	[[ -z "$$candidate" ]] && continue
	candidate_dev="$${candidate#/dev/}"
	candidate_dev="/dev/$$candidate_dev"
	candidate_info_json="$$(diskutil info -plist "$$candidate_dev" | plutil -convert json -o - -- -)"
	candidate_locked="$$(printf '%s\n' "$$candidate_info_json" | yq -p json -r '.Locked')"
	if [[ "$$candidate_locked" == "true" ]]; then
		encrypted_or_locked_detected=1
		echo "Skipping encrypted/locked APFS volume $$candidate_dev from $$image_path (Locked=true)"
		continue
	fi
	candidate_old_name="$$(printf '%s\n' "$$candidate_info_json" | yq -p json -r '.VolumeName')"
	candidate_old_name="$${candidate_old_name%%$$'\n'*}"
	if [[ -z "$$candidate_old_name" || "$$candidate_old_name" == "null" ]]; then
		continue
	fi
	if [[ "$$candidate_old_name" == "$$prefix"* ]]; then
		saw_prefixed_volume=1
		continue
	fi
	candidate_mount_point="$$(printf '%s\n' "$$candidate_info_json" | yq -p json -r '.MountPoint')"
	candidate_mount_point="$${candidate_mount_point%%$$'\n'*}"
	candidate_mounted_for_rename=0
	candidate_rename_mount_dir=""
	if [[ "$$rename_dry_run" == "1" ]]; then
		volume_dev="$$candidate_dev"
		old_name="$$candidate_old_name"
		mounted_for_rename=0
		rename_mount_dir=""
		break
	fi
	if [[ -z "$$candidate_mount_point" || "$$candidate_mount_point" == "null" ]]; then
		candidate_rename_mount_dir="$$(mktemp -p /tmp -d "tart-rename-mount.XXXXXX")"
		: "Mounting APFS volume $$candidate_dev at $$candidate_rename_mount_dir before rename"
		mount_err=""
		if ! mount_err="$$(diskutil mount -mountPoint "$$candidate_rename_mount_dir" "$$candidate_dev" 2>&1)"; then
			if [[ "$$container_mount_attempted" == "0" && -n "$$container_dev" ]]; then
				container_mount_attempted=1
				echo "Direct mount failed for $$candidate_dev; trying APFS container mount via $$container_dev"
				diskutil mountDisk "$$container_dev" >/dev/null 2>&1 || true
				candidate_info_json="$$(diskutil info -plist "$$candidate_dev" | plutil -convert json -o - -- -)"
				candidate_mount_point="$$(printf '%s\n' "$$candidate_info_json" | yq -p json -r '.MountPoint')"
				candidate_mount_point="$${candidate_mount_point%%$$'\n'*}"
				if [[ -n "$$candidate_mount_point" && "$$candidate_mount_point" != "null" ]]; then
					rm -rf "$$candidate_rename_mount_dir"
					candidate_rename_mount_dir=""
					volume_dev="$$candidate_dev"
					old_name="$$candidate_old_name"
					mounted_for_rename=0
					rename_mount_dir=""
					break
				fi
			fi
			if printf '%s\n' "$$mount_err" | grep -Eiq 'encrypted|locked|unlockVolume'; then
				encrypted_or_locked_detected=1
				echo "Skipping encrypted/locked APFS volume $$candidate_dev from $$image_path"
			else
				echo "Skipping unmountable APFS subvolume $$candidate_dev from $$image_path: $$mount_err"
			fi
			rm -rf "$$candidate_rename_mount_dir"
			continue
		fi
		candidate_mounted_for_rename=1
	fi
	volume_dev="$$candidate_dev"
	old_name="$$candidate_old_name"
	mounted_for_rename="$$candidate_mounted_for_rename"
	rename_mount_dir="$$candidate_rename_mount_dir"
	break
done <<< "$$volume_dev_candidates"
if [[ -z "$$volume_dev" || -z "$$old_name" ]]; then
	if [[ "$$rename_dry_run" == "1" ]]; then
		echo "DRY-RUN: no eligible APFS rename candidate resolved for $$image_path; skipping"
		cleanup_attached
		exit 0
	fi
	if [[ "$$saw_prefixed_volume" == "1" ]]; then
		echo "APFS volumes in $$image_path already use prefix '$$prefix'; nothing to rename."
		cleanup_attached
		exit 0
	fi
	if [[ "$$encrypted_or_locked_detected" == "1" ]]; then
		echo "Detected encrypted/locked APFS content in $$image_path; skipping"
		cleanup_attached
		exit 0
	fi
	echo "Failed to find a mountable APFS volume eligible for rename in $$image_path" >&2
	cleanup_attached
	exit 1
fi
new_name="$$prefix$$old_name"
if [[ "$$rename_dry_run" == "1" ]]; then
	echo "DRY-RUN: would rename APFS volume '$$old_name' -> '$$new_name' ($$volume_dev)"
else
	echo "Renaming APFS volume: '$$old_name' -> '$$new_name'"
	diskutil rename "$$volume_dev" "$$new_name" >/dev/null
fi
if [[ "$$mounted_for_rename" == "1" ]]; then
	if [[ "$$rename_dry_run" == "1" ]]; then
		: "DRY-RUN[disk]: skipping unmount of $$volume_dev"
	else
		diskutil unmount force "$$volume_dev" >/dev/null 2>&1 || true
		rm -rf "$$rename_mount_dir"
	fi
fi
cleanup_attached
trap - EXIT
endef

define .tart.cmd.rm-runtime-one
echo "=== rm-runtime: $$vm_name ==="
if [[ "$(.dry-run.tart.effective)" == "1" ]]; then
	: "DRY-RUN[tart]: would stop/delete VM $$vm_name and remove VM state artifacts"
	exit 0
fi
$(call .tart.run,stop "$$vm_name") >/dev/null 2>&1 || true
if $(call .tart.run,get "$$vm_name") >/dev/null 2>&1; then
	: "Deleting VM $$vm_name"
	$(call .tart.run,delete "$$vm_name")
else
	: "VM $$vm_name not found; skipping VM delete."
fi
vm_path="$(.tart.home)/vms/$$vm_name"
if [[ -d "$$vm_path" ]]; then
	: "Removing VM path $$vm_path"
	rm -rf "$$vm_path"
fi
if [[ "$$vm_name" == "$(.tart.stage1-vm.name)" ]]; then
	rm -f "$(.tart.stage1.vm.state)"
	: "Removed stage1 state file $(.tart.stage1.vm.state)"
fi
if [[ "$$vm_name" == "$(.tart.stage2-vm.name)" ]]; then
	rm -f "$(.tart.stage2.vm.state)"
	: "Removed stage2 state file $(.tart.stage2.vm.state)"
fi
if [[ "$$vm_name" == "$(.tart.stage3-vm.name)" ]]; then
	rm -f "$(.tart.stage3.vm.state)"
	: "Removed stage3 state file $(.tart.stage3.vm.state)"
fi
if [[ "$$vm_name" == "$(.tart.stage4-vm.name)" ]]; then
	rm -f "$(.tart.stage4.vm.state)"
	: "Removed stage4 state file $(.tart.stage4.vm.state)"
fi
rm -f "$(.tart.final.vm.state)"
: "Removed final VM state file $(.tart.final.vm.state)"
endef

define .tart.cmd.rm-role-disks-one
echo "=== rm-role-disks: $$vm_name ==="
if [[ "$(.dry-run.disk.effective)" == "1" ]]; then
	: "DRY-RUN[disk]: would remove role disks for $$vm_name under $(.tart.home)/disks/$$vm_name"
	exit 0
fi
disks_dir="$(.tart.home)/disks/$$vm_name"
rm -f "$$disks_dir"/*.asif 2>/dev/null || true
rm -rf "$$disks_dir"
: "Removed role disks for $$vm_name."
endef

define .tart.cmd.rm-owned-role-disks
echo "=== rm-owned-role-disks: $(.tart.disk.source-vm) ==="
owned_prefix="$(.tart.home)/disks/$(.tart.disk.source-vm)/"
removed_any=0
for img in $(.tart.disk.role.paths.effective); do
	if [[ "$$img" != "$$owned_prefix"* ]]; then
		: "Skipping non-owned role disk path: $$img"
		continue
	fi
	if [[ "$(.dry-run.disk.effective)" == "1" ]]; then
		if [[ -f "$$img" ]]; then
			: "DRY-RUN[disk]: would remove owned role disk $$img"
		else
			: "DRY-RUN[disk]: owned role disk missing (skip) $$img"
		fi
		continue
	fi
	if [[ -f "$$img" ]]; then
		rm -f "$$img"
		removed_any=1
		: "Removed owned role disk $$img"
	fi
done
if [[ "$(.dry-run.disk.effective)" != "1" ]]; then
	owned_dir="$(.tart.home)/disks/$(.tart.disk.source-vm)"
	if [[ -d "$$owned_dir" ]]; then
		rmdir "$$owned_dir" >/dev/null 2>&1 || true
	fi
	if [[ "$$removed_any" == "1" ]]; then
		: "Owned role-disk cleanup complete for $(.tart.disk.source-vm)."
	else
		: "No owned role disks were removed for $(.tart.disk.source-vm)."
	fi
fi
endef

define .vm.state.fragment.write
printf '%s\n' \
	'apiVersion: nxmatic.dev/v1alpha1' \
	'kind: VmStateFragment' \
	'vm:' \
	'  name: "$(1)"' \
	'  path: "$(2)"' \
	'state:' \
	'  stage: "$(3)"' \
	'  profile: "$(4)"' \
	"  generated_at: \"$$(date -u +%Y-%m-%dT%H:%M:%SZ)\"" > "$@"
endef

.PHONY: help validate validate-packer validate-tart clone-from-vanilla ensure-root-disk-size prepare-disks check-prefixed-role-disks build build-rootfs build-image build-system-only build-with-role-disks build-nix-store-volume build-nix-install build-nxmatic build-super-token-refresh stage-grow stage-nix-store-volume stage-nix-install stage-nxmatic stage-super-token-refresh stage1 stage2 stage3 stage4 stage5 cleanup-stages run console run-recovery-console run-script hotfix-runtime-sync info disks-info rename-disk-volume rename-disk-volumes rename-disk-attached-volumes rename-foreign-role-disk-volumes apfs-ownership-policy rm-runtime rm-runtime-one rm-role-disks rm-role-disks-one rm-owned-role-disks init-foreign-home rm refresh-console refresh promote shell-fmt shell-check fmt FORCE

# Curated set of targets shown by `make help`
.help.targets ?= help validate validate-packer validate-tart build stage1 stage2 stage3 stage4 stage5 cleanup-stages build-with-role-disks run console run-recovery-console run-script hotfix-runtime-sync info disks-info rename-disk-volumes rename-disk-attached-volumes rename-foreign-role-disk-volumes apfs-ownership-policy init-foreign-home refresh-console refresh promote rm rm-runtime rm-role-disks shell-fmt shell-check fmt

# Curated set of command-line variables shown by `make help`
.help.vars ?= .interactive .debug .experimental .skip .dry-run .dry-run.tart .dry-run.disk .dry-run.packer .dry-run.apfs.ownership .tart.vm.name .tart.vm.names .tart.rm.vm.name .tart.base.ref .tart.base.home .tart.base.link-source .tart.stage.name-prefix .tart.stage.use-dedicated-homes .tart.stage.tart-home-root .tart.stage.link-source-vm .tart.stage.cleanup.on-success .tart.stage.cleanup.keep-logs .tart.stage.cleanup.include-stage1 .tart.stage1.tart-home .tart.stage2.tart-home .tart.stage3.tart-home .tart.stage4.tart-home .tart.update.from-vm .tart.update.to-vm .tart.update.profile .tart.update.relax-session-tweaks .tart.update.tart-home .tart.update.link-role-disks .tart.update.link-source-vm .tart.update.source-vm-alias .provision.profile .attach-data-disk-during-build .tart.disk.recreate .tart.clone.force .tart.disk.source-vm .tart.disk.prefix.owner .tart.disk.prefix.enforce .tart.disk.rename.home .tart.run.recovery .tart.run.vnc .tart.run.net-bridged .tart.run.attach-foreign-renamed .tart.run.extra-disks .tart.run.extra-disks.from-vm .tart.run.extra-disks.allow-duplicate-roles .tart.run.extra-disk.opts .tart.run.script.path .tart.run.script.console .hotfix.control.root .hotfix.stage .rm.skip-owned-disks-when-add-renamed .tart.disk.path .tart.disk.path.rename .tart.disk.name .tart.disk.volume-devs .apfs.ownership.mode .apfs.ownership.all-roles .apfs.ownership.include-system-mounts .apfs.ownership.images .macos.relax-session-tweaks .account.primary-name .account.secondary-name .auto-login.user TART_HOME TART_HOME_FOREIGN TART_ATTACH_FOREIGN_RENAMED

.help.vars += TART_EXTRA_DISKS_ADD_RENAMED TART_EXTRA_DISKS_RENAMED_FROM_VM
.no-pager ?= 0

$(.env.file):
	: "Generating $@ from Make variables"
	$(file >$@,$(.env.file.content))

init-foreign-home: ## Initialize foreign Tart home with same top-level structure (vms/disks)
	mkdir -p "$(.tart.home.foreign)/vms" "$(.tart.home.foreign)/disks"
	: "Initialized foreign Tart home at $(.tart.home.foreign)."

help: ## Show available targets
	set +x
	emit_help() {
		: "Generating help from rules"
		printf "\nPreamble:\n"
		printf "  Build profile: staged Tahoe image pipeline with explicit stage artifacts.\n"
		printf "  Purpose: deterministic grow -> nix-store -> nix-darwin -> nxmatic -> token-refresh flow.\n"
		printf "  Help view: curated (see .help.targets).\n"
		printf "\nTargets:\n"
		{ \
			(grep -he '^[a-zA-Z0-9_.-]\+:.*##' $(MAKEFILE_LIST) || true) | sed -e 's/:.*##/:\t/' ; \
			(grep -he '^\.PHONY:.*##' $(MAKEFILE_LIST) || true) | sed -e 's/ *##/:\t/' | sed -e 's/^\.PHONY: *//' ; \
		} | awk -F ':\t' 'BEGIN { split("$(.help.targets)", keep, " "); for (i in keep) wanted[keep[i]] = 1 } wanted[$$1] && !seen[$$1]++ { printf "  %-18s %s\n", $$1, $$2 }'
		printf "\nCommand-line variables:\n"
		printf "  Usage: make <target> <var>=<value>\n"
		$(foreach v,$(.help.vars),printf "  %-30s %s\n" "$(v)" "$($(v))";)
		printf "\nSummary:\n"
		printf "  Canonical build target is make build (stage1..stage5).\n"
		printf "  Stage5 logs in as super, refreshes primary token, and keeps canonical autologin on super.\n"
		printf "  Update autologin in live VM manually when desired for user workflows.\n"
	}
	if [[ -t 1 && "$(.no-pager)" != "1" && -z "${NO_PAGER:-}" ]]; then
		read -r -a pager_parts <<< "${PAGER:-less -FRX}"
		pager_bin="${pager_parts[0]:-}"
		if [[ -n "$$pager_bin" ]] && command -v "$$pager_bin" >/dev/null 2>&1; then
			emit_help | "${pager_parts[@]}"
		else
			emit_help
		fi
	else
		emit_help
	fi

validate: validate-packer validate-tart shell-check ## Run all validations (packer, tart, shell)

validate-packer: $(.env.file) ## Validate the Packer template
	$(call .packer.run,validate $(strip $(.packer.vars.active)) $(.template))

validate-tart: $(.env.file) ## Validate Tart CLI access
	$(call .env.load)
	if [[ "$(.dry-run.tart.effective)" == "1" ]]; then
		echo "DRY-RUN[tart]: TART_HOME=\"$${TART_HOME}\" TART_HOME_FOREIGN=\"$${TART_HOME_FOREIGN}\" $(.tart.cmd) --version"
		echo "DRY-RUN[tart]: TART_HOME=\"$${TART_HOME}\" TART_HOME_FOREIGN=\"$${TART_HOME_FOREIGN}\" $(.tart.cmd) list"
	else
		$(.tart.cmd) --version >/dev/null
		$(.tart.cmd) list >/dev/null
	fi

clone-from-vanilla: validate-tart $(.env.file) ## Clone Tahoe vanilla image into .tart.vm.name (set .tart.clone.force=1 to replace)
	if [[ "$(.tart.clone.force)" == "1" ]]; then
		if $(call .tart.run,get "$(.tart.vm.name)") >/dev/null 2>&1; then
			$(call .tart.run,delete "$(.tart.vm.name)")
		fi
	fi
	if $(call .tart.run,get "$(.tart.vm.name)") >/dev/null 2>&1; then
		: "VM $(.tart.vm.name) already exists; skipping clone (set .tart.clone.force=1 to replace)."
	else
		$(call .tart.run,clone "$(.tart.base.ref)" "$(.tart.vm.name)")
	fi
	$(MAKE) ensure-root-disk-size .tart.vm.name="$(.tart.vm.name)" .tart.disk.root.max-size-gb="$(.tart.disk.root.max-size-gb)"

ensure-root-disk-size: validate-tart $(.env.file) ## Ensure VM root disk is grown to .tart.disk.root.max-size-gb when VM exists
	if $(call .tart.run,get "$(.tart.vm.name)") >/dev/null 2>&1; then
		: "Ensuring root disk size for $(.tart.vm.name): target $(.tart.disk.root.max-size-gb)G"
		$(call .tart.run,set "$(.tart.vm.name)" --disk-size "$(.tart.disk.root.max-size-gb)")
	else
		: "VM $(.tart.vm.name) not found; skipping root disk resize."
	fi

prepare-disks: ## Create role disk images when enabled and missing
ifneq ($(call opt-enabled,.attach-data-disk-during-build),)
	$(call .tart.disk.cmd.ensure-parent,$(.tart.disk.user.image-path.effective))
	$(call .tart.disk.cmd.ensure-parent,$(.tart.disk.user-library.image-path.effective))
	$(call .tart.disk.cmd.ensure-parent,$(.tart.disk.git-bare-store.image-path.effective))
	$(call .tart.disk.cmd.ensure-parent,$(.tart.disk.git-store.image-path.effective))
	$(call .tart.disk.cmd.ensure-parent,$(.tart.disk.nix-store.image-path.effective))
	$(call .tart.disk.cmd.ensure-parent,$(.tart.disk.user-build-chains-cache.image-path.effective))
	$(call .tart.disk.cmd.ensure-parent,$(.tart.disk.vm-images.image-path.effective))
	$(call .tart.disk.cmd.prepare-image,Users:$(.data.home-user),$(.tart.disk.user.image-path.effective),$(.tart.disk.user.max-size-gb))
	$(call .tart.disk.cmd.prepare-image,Users:$(.data.home-user) Build Chains Cache,$(.tart.disk.user-build-chains-cache.image-path.effective),$(.tart.disk.user-build-chains-cache.max-size-gb))
	$(call .tart.disk.cmd.prepare-image,Users:$(.data.home-user) Library Cache,$(.tart.disk.user-library.image-path.effective),$(.tart.disk.user-library.max-size-gb))
	$(call .tart.disk.cmd.prepare-image,Users:$(.data.home-user) VM Images,$(.tart.disk.vm-images.image-path.effective),$(.tart.disk.vm-images.max-size-gb))
	$(call .tart.disk.cmd.prepare-image,Git Store,$(.tart.disk.git-store.image-path.effective),$(.tart.disk.git-store.max-size-gb))
	$(call .tart.disk.cmd.prepare-image,Git Bare Store,$(.tart.disk.git-bare-store.image-path.effective),$(.tart.disk.git-bare-store.max-size-gb))
	$(call .tart.disk.cmd.prepare-image,Nix Store,$(.tart.disk.nix-store.image-path.effective),$(.tart.disk.nix-store.max-size-gb))
else
	: "Role disk attachment disabled (.attach-data-disk-during-build=$(strip $(.attach-data-disk-during-build))); skipping image preparation."
endif

build-image: $(.env.file) ## Internal: execute packer build with active template/flags
	if [[ "$(.tart.base.link-source)" == "1" && "$(.tart.stage.link-source-vm)" == "1" && "$(.tart.base.home)" != "$(.tart.home)" ]]; then
		src_vm_dir="$(.tart.base.home)/vms/$(.tart.base.ref)"
		dst_vm_dir="$(.tart.home)/vms/$(.tart.base.ref)"
		if [[ "$(.dry-run.tart.effective)" == "1" ]]; then
			if [[ ! -e "$$src_vm_dir" ]]; then
				echo "DRY-RUN[tart]: staged base source is currently missing (expected once prior stage is built): $$src_vm_dir"
			fi
			echo "DRY-RUN[tart]: would symlink staged base VM $$src_vm_dir -> $$dst_vm_dir"
		else
			if [[ ! -e "$$src_vm_dir" ]]; then
				echo "Missing source VM directory for staged base link: $$src_vm_dir" >&2
				exit 2
			fi
			mkdir -p "$(.tart.home)/vms"
			ln -sfn "$$src_vm_dir" "$$dst_vm_dir"
		fi
	fi
	if [[ "$(call to-bool,$(.attach-data-disk-during-build))" == "true" ]]; then $(MAKE) prepare-disks TART_HOME="$(.tart.home)" TART_HOME_FOREIGN="$(.tart.home.foreign)" .tart.disk.recreate="$(.tart.disk.recreate)" .attach-data-disk-during-build="$(.attach-data-disk-during-build)" .tart.disk.blank.fs="$(.tart.disk.blank.fs)"; else : "Skipping prepare-disks because .attach-data-disk-during-build=$(strip $(.attach-data-disk-during-build))"; fi
	$(call .packer.run,build $(.packer.flags.interactive) $(.packer.flags.failure) $(strip $(.packer.vars.active)) $(.template))

$(.tart.stage1.vm.path): ## Ensure stage1 VM artifact exists (bootstraps via build-system-only when missing)
	if [[ -d "$@" ]]; then
		: "Reusing existing stage1 VM artifact: $@"
	else
		: "Stage1 VM artifact missing: $@; bootstrapping via build-system-only"
		$(MAKE) build-system-only .tart.vm.name="$(.tart.stage1-vm.name)"
	fi

$(.tart.stage1.vm.state): $(.tart.stage1.vm.path) ## Track stage1 VM artifact readiness state
	if [[ -d "$(.tart.stage1.vm.path)" ]]; then
		$(call .vm.state.fragment.write,$(.tart.stage1-vm.name),$(.tart.stage1.vm.path),stage1,grow)
		: "Updated stage1 VM state: $@"
	else
		: "Stage1 VM path missing unexpectedly: $(.tart.stage1.vm.path)"
		exit 1
	fi

build-rootfs: $(.tart.stage1.vm.state) ## Ensure stage1 VM artifact exists and is grown

$(.tart.stage2.vm.path): $(.tart.stage1.vm.state) ## Ensure stage2 VM artifact exists (nix-store-volume profile)
	if [[ -d "$@" ]]; then
		: "Reusing existing stage2 VM artifact: $@"
	else
		: "Stage2 VM artifact missing: $@; bootstrapping via build-nix-store-volume"
		$(MAKE) build-nix-store-volume
	fi

$(.tart.stage2.vm.state): $(.tart.stage2.vm.path) ## Track stage2 VM artifact readiness state
	if [[ -d "$(.tart.stage2.vm.path)" ]]; then
		$(call .vm.state.fragment.write,$(.tart.stage2-vm.name),$(.tart.stage2.vm.path),stage2,nix-store-volume)
		: "Updated stage2 VM state: $@"
	else
		: "Stage2 VM path missing unexpectedly: $(.tart.stage2.vm.path)"
		exit 1
	fi

$(.tart.stage3.vm.path): $(.tart.stage2.vm.state) ## Ensure stage3 VM artifact exists (nix-install profile)
	if [[ -d "$@" ]]; then
		: "Reusing existing stage3 VM artifact: $@"
	else
		: "Stage3 VM artifact missing: $@; bootstrapping via build-nix-install"
		$(MAKE) build-nix-install
	fi

$(.tart.stage3.vm.state): $(.tart.stage3.vm.path) ## Track stage3 VM artifact readiness state
	if [[ -d "$(.tart.stage3.vm.path)" ]]; then
		$(call .vm.state.fragment.write,$(.tart.stage3-vm.name),$(.tart.stage3.vm.path),stage3,nix-install)
		: "Updated stage3 VM state: $@"
	else
		: "Stage3 VM path missing unexpectedly: $(.tart.stage3.vm.path)"
		exit 1
	fi

$(.tart.stage4.vm.path): $(.tart.stage3.vm.state) ## Ensure stage4 VM artifact exists (nxmatic profile)
	if [[ -d "$@" ]]; then
		: "Reusing existing stage4 VM artifact: $@"
	else
		: "Stage4 VM artifact missing: $@; bootstrapping via build-nxmatic"
		$(MAKE) build-nxmatic
	fi

$(.tart.stage4.vm.state): $(.tart.stage4.vm.path) ## Track stage4 VM artifact readiness state
	if [[ -d "$(.tart.stage4.vm.path)" ]]; then
		$(call .vm.state.fragment.write,$(.tart.stage4-vm.name),$(.tart.stage4.vm.path),stage4,nxmatic)
		: "Updated stage4 VM state: $@"
	else
		: "Stage4 VM path missing unexpectedly: $(.tart.stage4.vm.path)"
		exit 1
	fi

$(.tart.final.vm.state): $(.tart.vm.path) ## Track final VM artifact readiness state
	if [[ -d "$(.tart.vm.path)" ]]; then
		$(call .vm.state.fragment.write,$(.tart.vm.name),$(.tart.vm.path),final,super-token-refresh)
		: "Updated final VM state: $@"
	else
		: "Final VM path missing unexpectedly: $(.tart.vm.path)"
		exit 1
	fi

build: stage5 ensure-root-disk-size ## Canonical 5-stage flow: grow -> nix-store-volume -> nix-darwin -> nxmatic -> super-token-refresh
	if [[ "$(call opt-enabled,.tart.stage.cleanup.on-success)" == "1" ]]; then
		$(MAKE) cleanup-stages
	else
		: "Skipping post-success stage cleanup (.tart.stage.cleanup.on-success=$(strip $(.tart.stage.cleanup.on-success)))."
	fi

cleanup-stages: ## Remove intermediate stage artifacts after successful build while preserving stage logs in active Tart home
	stages="stage2 stage3 stage4"
	if [[ "$(call opt-enabled,.tart.stage.cleanup.include-stage1)" == "1" ]]; then
		stages="stage1 $$stages"
	fi
	mkdir -p "$(.tart.home)/vms"
	for stage in $$stages; do
		case "$$stage" in
			stage1)
				stage_home="$(.tart.stage1.tart-home)"
				stage_vm="$(.tart.stage1-vm.name)"
				stage_state_file="$(.tart.stage1.vm.state)"
				;;
			stage2)
				stage_home="$(.tart.stage2.tart-home)"
				stage_vm="$(.tart.stage2-vm.name)"
				stage_state_file="$(.tart.stage2.vm.state)"
				;;
			stage3)
				stage_home="$(.tart.stage3.tart-home)"
				stage_vm="$(.tart.stage3-vm.name)"
				stage_state_file="$(.tart.stage3.vm.state)"
				;;
			stage4)
				stage_home="$(.tart.stage4.tart-home)"
				stage_vm="$(.tart.stage4-vm.name)"
				stage_state_file="$(.tart.stage4.vm.state)"
				;;
			*)
				echo "Unknown stage $$stage" >&2
				exit 2
				;;
		esac

		if [[ "$(call opt-enabled,.tart.stage.cleanup.keep-logs)" == "1" ]]; then
			src_log="$$stage_home/vms/$$stage_vm.packer.log"
			dst_log="$(.tart.home)/vms/$$stage_vm.packer.log"
			if [[ -f "$$src_log" ]]; then
				if [[ "$(.dry-run.packer.effective)" == "1" ]]; then
					echo "DRY-RUN[packer]: would preserve stage log $$src_log -> $$dst_log"
				else
					cp -f "$$src_log" "$$dst_log"
					: "Preserved stage log: $$dst_log"
				fi
			fi
		fi

		if [[ "$(.dry-run.tart.effective)" == "1" ]]; then
			echo "DRY-RUN[tart]: would stop/delete stage VM $$stage_vm from home $$stage_home"
		else
			if TART_HOME="$$stage_home" $(.tart.cmd) get "$$stage_vm" >/dev/null 2>&1; then
				TART_HOME="$$stage_home" $(.tart.cmd) stop "$$stage_vm" >/dev/null 2>&1 || true
				TART_HOME="$$stage_home" $(.tart.cmd) delete "$$stage_vm" >/dev/null 2>&1 || true
			fi
		fi

		if [[ "$(.dry-run.disk.effective)" == "1" ]]; then
			echo "DRY-RUN[disk]: would remove $$stage_home/disks/$$stage_vm and $$stage_home/vms/$$stage_vm"
		else
			rm -rf "$$stage_home/disks/$$stage_vm" "$$stage_home/vms/$$stage_vm"
		fi

		if [[ "$(.dry-run.disk.effective)" == "1" ]]; then
			echo "DRY-RUN[disk]: would remove stage state file $$stage_state_file"
		else
			rm -f "$$stage_state_file"
		fi

		if [[ "$$stage_home" != "$(.tart.home)" ]]; then
			if [[ "$(.dry-run.disk.effective)" == "1" ]]; then
				echo "DRY-RUN[disk]: would prune empty stage home $$stage_home"
			else
				rmdir "$$stage_home/vms" >/dev/null 2>&1 || true
				rmdir "$$stage_home/disks" >/dev/null 2>&1 || true
				rmdir "$$stage_home" >/dev/null 2>&1 || true
			fi
		fi
	done

build-system-only: .template=$(.template.grow)
build-system-only: .attach-data-disk-during-build=0
build-system-only: .recovery.partition.mode=relocate
build-system-only: .packer.vars.override=$(.packer.vars.grow)
build-system-only: .tart.base.home=$(.tart.home)
build-system-only: .tart.base.link-source=0
build-system-only: build-image ## Build with vanilla grow-only template (recommended first bootstrap step)

stage1: override .tart.vm.name:=$(.tart.stage1-vm.name)
stage1: TART_HOME=$(.tart.stage1.tart-home)
stage1: build-system-only ## Stage 1 canonical flow: root-only bootstrap build

stage-grow: stage1 ## Alias: stage 1 grow-only artifact

build-nix-store-volume: .template=$(.template.customize)
build-nix-store-volume: override .tart.vm.name:=$(.tart.stage2-vm.name)
build-nix-store-volume: override .tart.base.ref:=$(.tart.stage1-vm.name)
build-nix-store-volume: .tart.base.home=$(.tart.stage1.tart-home)
build-nix-store-volume: .tart.base.link-source=1
build-nix-store-volume: .attach-data-disk-during-build=1
build-nix-store-volume: .recovery.partition.mode=keep
build-nix-store-volume: .provision.profile=nix-store-volume
build-nix-store-volume: TART_HOME=$(.tart.stage2.tart-home)
build-nix-store-volume: build-image ## Build stage2 artifact: initialize role volumes (incl Nix store volume)

stage-nix-store-volume: $(.tart.stage2.vm.state) ## Stage 2 artifact: nix-store-volume

build-nix-install: .template=$(.template.customize)
build-nix-install: override .tart.vm.name:=$(.tart.stage3-vm.name)
build-nix-install: override .tart.base.ref:=$(.tart.stage2-vm.name)
build-nix-install: .tart.base.home=$(.tart.stage2.tart-home)
build-nix-install: .tart.base.link-source=1
build-nix-install: .attach-data-disk-during-build=1
build-nix-install: .recovery.partition.mode=keep
build-nix-install: .provision.profile=nix-install
build-nix-install: TART_HOME=$(.tart.stage3.tart-home)
build-nix-install: build-image ## Build stage3 artifact: nix installer/bootstrap execution

stage-nix-install: $(.tart.stage3.vm.state) ## Stage 3 artifact: nix-install

build-nxmatic: .template=$(.template.customize)
build-nxmatic: override .tart.vm.name:=$(.tart.stage4-vm.name)
build-nxmatic: override .tart.base.ref:=$(.tart.stage3-vm.name)
build-nxmatic: .tart.base.home=$(.tart.stage3.tart-home)
build-nxmatic: .tart.base.link-source=1
build-nxmatic: .attach-data-disk-during-build=1
build-nxmatic: .recovery.partition.mode=keep
build-nxmatic: .provision.profile=nxmatic
build-nxmatic: TART_HOME=$(.tart.stage4.tart-home)
build-nxmatic: build-image ## Build stage4 artifact: nxmatic customization

stage-nxmatic: $(.tart.stage4.vm.state) ## Stage 4 artifact: nxmatic customization

build-super-token-refresh: .template=$(.template.customize)
build-super-token-refresh: override .tart.base.ref:=$(.tart.stage4-vm.name)
build-super-token-refresh: .tart.base.home=$(.tart.stage4.tart-home)
build-super-token-refresh: .tart.base.link-source=1
build-super-token-refresh: .attach-data-disk-during-build=1
build-super-token-refresh: .recovery.partition.mode=keep
build-super-token-refresh: .provision.profile=super-token-refresh
build-super-token-refresh: .auto-login.user=$(.account.secondary-name)
build-super-token-refresh: .bootstrap.ssh.user=$(.account.secondary-name)
build-super-token-refresh: .bootstrap.ssh.password=$(.account.secondary-password)
build-super-token-refresh: TART_HOME=$(.tart.home)
build-super-token-refresh: build-image ## Build stage5 artifact: super autologin + primary token refresh

stage-super-token-refresh: $(.tart.stage4.vm.state) build-super-token-refresh $(.tart.final.vm.state) ## Stage 5 artifact: final VM

stage2: stage-nix-store-volume ## Stage 2 canonical flow: nix store volume stage
stage3: stage-nix-install ## Stage 3 canonical flow: nix-darwin stage
stage4: stage-nxmatic ## Stage 4 canonical flow: nxmatic customization stage
stage5: stage-super-token-refresh ## Stage 5 canonical flow: super token refresh + final login policy

build-with-role-disks: .template=$(.template.customize)
build-with-role-disks: .tart.base.ref=$(.tart.stage1-vm.name)
build-with-role-disks: .attach-data-disk-during-build=1
build-with-role-disks: .recovery.partition.mode=keep
build-with-role-disks: .provision.profile=full
build-with-role-disks: build-image ## Full rebuild with role disks attached (base=stage1 artifact)

check-prefixed-role-disks: ## Validate role-disk volume names match '<owner> - ' when .tart.disk.prefix.enforce=1
	if [[ "$(.tart.disk.prefix.enforce)" != "1" ]]; then
		: "Prefix enforcement disabled (.tart.disk.prefix.enforce=$(.tart.disk.prefix.enforce)); skipping role-disk prefix checks."
		exit 0
	fi
	owner_prefix="$(.tart.disk.prefix.owner) - "
	for img in $(.tart.disk.role.paths.effective); do
		if [[ ! -f "$$img" ]]; then
			echo "Missing role disk image: $$img" >&2
			exit 2
		fi
		json="$$(diskutil image attach -nomount -nobrowse -plist "$$img" | plutil -convert json -o - -- -)"
		detach_targets="$$(printf '%s\n' "$$json" | yq -p json -r '."system-entities"[] | select(has("dev-entry")) | ."dev-entry" | select(test("^(/dev/)?disk[0-9]+$$"))' | sed -E 's#^/dev/##' | awk '!seen[$$0]++ { print "/dev/" $$0 }')"
		matched=0
		while IFS= read -r vol_name; do
			[[ -z "$$vol_name" || "$$vol_name" == "null" ]] && continue
			if [[ "$$vol_name" == "$$owner_prefix"* ]]; then
				matched=1
				break
			fi
		done <<< "$$(printf '%s\n' "$$json" | yq -p json -r '."system-entities"[] | select((."filesystem-type" == "apfs") or (."content-hint" == "Apple_APFS_Volume")) | ."volume-name" // empty')"
		while IFS= read -r dev; do
			[[ -z "$$dev" ]] && continue
			diskutil detach "$$dev" >/dev/null 2>&1 || true
		done <<< "$$detach_targets"
		if [[ "$$matched" != "1" ]]; then
			echo "Role disk does not match required owner prefix '$$owner_prefix': $$img" >&2
			exit 1
		fi
	done

run: prepare-disks $(if $(filter 1,$(.tart.disk.prefix.enforce)),check-prefixed-role-disks,) ensure-root-disk-size $(.env.file) ## Run the built VM with all role disks attached
	declare -a extra_from_vm_args=()
	$(.tart.run.extra.disk.args.from-vm.shell)
	$(call .env.load)
	if [[ "$(.dry-run.tart.effective)" == "1" ]]; then
		printf 'DRY-RUN[tart]: %q ' TART_HOME="$${TART_HOME}" TART_HOME_FOREIGN="$${TART_HOME_FOREIGN}" $(.tart.cmd) run $(.tart.vm.name) $(strip $(.tart.run.disk.args) $(.tart.run.extra.disk.args) $(.tart.run.extra-args)) "$${extra_from_vm_args[@]}"
		echo
	else
		$(.tart.cmd) run $(.tart.vm.name) $(strip $(.tart.run.disk.args) $(.tart.run.extra.disk.args) $(.tart.run.extra-args)) "$${extra_from_vm_args[@]}"
	fi

console: prepare-disks $(if $(filter 1,$(.tart.disk.prefix.enforce)),check-prefixed-role-disks,) ensure-root-disk-size $(.env.file) ## Run VM with console troubleshooting defaults (Screen Sharing VNC + optional bridge/recovery)
	declare -a extra_from_vm_args=()
	$(.tart.run.extra.disk.args.from-vm.shell)
	$(call .env.load)
	if [[ "$(.dry-run.tart.effective)" == "1" ]]; then
		printf 'DRY-RUN[tart]: %q ' TART_HOME="$${TART_HOME}" TART_HOME_FOREIGN="$${TART_HOME_FOREIGN}" $(.tart.cmd) run $(.tart.vm.name) $(strip $(.tart.run.console.args) $(.tart.run.disk.args) $(.tart.run.extra.disk.args) $(.tart.run.extra-args)) "$${extra_from_vm_args[@]}"
		echo
	else
		$(.tart.cmd) run $(.tart.vm.name) $(strip $(.tart.run.console.args) $(.tart.run.disk.args) $(.tart.run.extra.disk.args) $(.tart.run.extra-args)) "$${extra_from_vm_args[@]}"
	fi

run-recovery-console: .tart.run.recovery=1
run-recovery-console: console ## Run VM in recovery mode with console troubleshooting defaults

run-script: prepare-disks $(if $(filter 1,$(.tart.disk.prefix.enforce)),check-prefixed-role-disks,) ensure-root-disk-size $(.env.file) ## Generate/update executable VM launcher script from current run settings
	declare -a extra_from_vm_args=()
	$(.tart.run.extra.disk.args.from-vm.shell)
	$(call .env.load)
	script_path="$(.tart.run.script.path)"
	mkdir -p "$$(dirname "$$script_path")"
	declare -a cmd_parts=(
		env
		"TART_HOME=$${TART_HOME}"
		"TART_HOME_FOREIGN=$${TART_HOME_FOREIGN}"
		"$(.tart.cmd)"
		run
		"$(.tart.vm.name)"
		$(.tart.run.script.args)
		"$${extra_from_vm_args[@]}"
	)
	{
		printf '%s\n' '#!/usr/bin/env -S bash -euxo pipefail'
		printf '\n'
		printf 'exec'
		for part in "$${cmd_parts[@]}"; do
			[[ -z "$$part" ]] && continue
			printf ' %q' "$$part"
		done
		printf '\n'
	} > "$$script_path"
	chmod 0755 "$$script_path" 2>/dev/null || true
	: "Generated VM launcher script: $$script_path"

hotfix-runtime-sync: run-script ## Sync active-stage runtime hotfix assets into versioned control folder (prunes stale stage dirs)
	root_dir="$(.hotfix.control.root)"
	stage="$(.hotfix.stage.effective)"
	stage_dir="$$root_dir/$$stage"
	script_path="$(.tart.run.script.path)"

	mkdir -p "$$root_dir" "$$stage_dir"

	for d in "$$root_dir"/*; do
		[[ -d "$$d" ]] || continue
		if [[ "$$d" != "$$stage_dir" ]]; then
			rm -rf "$$d"
		fi
	done

	cp -f "$$script_path" "$$stage_dir/$(.tart.vm.name).sh"

	printf '%s\n' "$$stage" > "$$root_dir/ACTIVE_STAGE"
	printf '%s\n' \
		"vm=$(.tart.vm.name)" \
		"stage=$$stage" \
		"generated_at=$$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
		"run_script=$$(basename "$$script_path")" \
		> "$$stage_dir/hotfix-assets.env"

	: "Synced active-stage hotfix assets to $$stage_dir"

info: $(.env.file) ## Show Tart VM details
	$(call .tart.run,list)
	$(call .tart.run,get $(.tart.vm.name))

disks-info: ## Show role disk files and sizes
	$(call .tart.disk.cmd.show-info,Data-Home-$(.data.home-user),$(.tart.disk.user.image-path.effective))
	$(call .tart.disk.cmd.show-info,Users:$(.data.home-user) Library Cache,$(.tart.disk.user-library.image-path.effective))
	$(call .tart.disk.cmd.show-info,Git Bare Store,$(.tart.disk.git-bare-store.image-path.effective))
	$(call .tart.disk.cmd.show-info,Git Store,$(.tart.disk.git-store.image-path.effective))
	$(call .tart.disk.cmd.show-info,Nix Store,$(.tart.disk.nix-store.image-path.effective))
	$(call .tart.disk.cmd.show-info,Users:$(.data.home-user) Build Chains Cache,$(.tart.disk.user-build-chains-cache.image-path.effective))
	$(call .tart.disk.cmd.show-info,Users:$(.data.home-user) VM Images,$(.tart.disk.vm-images.image-path.effective))

rename-disk-volume: ## Rename APFS volume inside one ASIF image (.tart.disk.path required; .tart.disk.path.rename optional override; use .dry-run.disk=1 to avoid rename writes)
	if [[ -z "$(strip $(.tart.disk.path.effective))" ]]; then
		echo "Missing required .tart.disk.path (or .tart.disk.path.rename)" >&2
		exit 2
	fi
	prefix="$(.tart.disk.name.effective)"
	image_path="$(.tart.disk.path.effective)"
	$(.tart.disk.cmd.rename-volume)

rename-disk-volumes: rename-disk-volumes-check $(.tart.vm.name.paths.rename-targets) ## Rename all ASIF APFS volumes from .tart.vm.name with '<vm> - ' prefix by default

rename-foreign-role-disk-volumes: ## Rename APFS labels in foreign role disks with '<vm> - ' ownership prefix (space-safe)
	disks_dir="$(.tart.home.foreign)/disks/$(.tart.vm.name)"
	if [[ ! -d "$$disks_dir" ]]; then
		echo "No foreign disk directory found: $$disks_dir" >&2
		exit 2
	fi
	found=0
	while IFS= read -r -d '' img; do
		found=1
		$(MAKE) rename-disk-volume \
			.tart.disk.path.rename="$$img" \
			.tart.disk.name="$(.tart.vm.name) - " \
			.dry-run="$(.dry-run)" \
			.dry-run.disk="$(.dry-run.disk.effective)"
	done < <(find "$$disks_dir" -maxdepth 1 -type f -name '*.asif' -print0 | sort -z)
	if [[ "$$found" != "1" ]]; then
		echo "No foreign .asif images found in $$disks_dir" >&2
		exit 2
	fi

rename-disk-attached-volumes: $(.tart.disk.volume-devs.rename-targets) ## Rename explicit attached APFS volume devices from .tart.disk.volume-devs for one .tart.disk.path
	if [[ -z "$(strip $(.tart.disk.path.effective))" ]]; then
		echo "Missing required .tart.disk.path (or .tart.disk.path.rename)" >&2
		exit 2
	fi
	if [[ -z "$(strip $(.tart.disk.volume-devs))" ]]; then
		echo "Missing required .tart.disk.volume-devs (space-separated disk identifiers, e.g. disk7s1 /dev/disk7s2)" >&2
		exit 2
	fi

rename-disk-volumes-check:
	if [[ -z "$(strip $(.tart.vm.name))" ]]; then
		echo "Missing required .tart.vm.name" >&2
		exit 2
	fi
	if [[ -z "$(strip $(.tart.vm.name.paths))" ]]; then
		echo "No ASIF images found under $(.tart.disk.rename.home)/disks/$(.tart.vm.name)" >&2
		exit 2
	fi

%~rename: FORCE ## Internal: rename APFS volume for one ASIF path (dynamic dependency pattern)
	prefix="$(.tart.disk.name.effective)"
	image_path="$(patsubst %~rename,%,$@)"
	$(.tart.disk.cmd.rename-volume)

%~rename-volume: .tart.disk.volume-dev=$(patsubst %~rename-volume,%,$@)
%~rename-volume: FORCE ## Internal: rename one explicit attached APFS volume device for .tart.disk.path
	prefix="$(.tart.disk.name.effective)"
	image_path="$(.tart.disk.path.effective)"
	$(.tart.disk.cmd.rename-volume)

apfs-ownership-policy: ## Apply APFS ownership policy (default disable for portability); supports .apfs.ownership.* vars
	if [[ ! -f "$(.apfs.ownership.script)" ]]; then
		echo "Missing script: $(.apfs.ownership.script)" >&2
		exit 2
	fi
	args=( --ownership-mode "$(.apfs.ownership.mode)" )
	if [[ "$(.dry-run.apfs.ownership.effective)" == "1" ]]; then args+=( --dry-run ); fi
	if [[ "$(.apfs.ownership.all-roles)" == "1" ]]; then args+=( --all-roles ); fi
	if [[ "$(.apfs.ownership.include-system-mounts)" == "1" ]]; then args+=( --include-system-mounts ); fi
	if [[ -n "$(strip $(.apfs.ownership.images))" ]]; then
		for img in $(.apfs.ownership.images); do
			args+=( --image "$$img" )
		done
	fi
	bash "$(.apfs.ownership.script)" "$${args[@]}"

rm-runtime: validate-tart $(.env.file) $(.tart.vm.names.rm-runtime-targets) ## Stop runtime and remove VM artifact/state for each name in .tart.vm.names

%~rm-runtime: FORCE
	vm_name="$${@%~rm-runtime}"
	$(.tart.cmd.rm-runtime-one)

rm-runtime-one: validate-tart $(.env.file) ## Internal: stop runtime and remove VM artifact/state for .tart.vm.name
	vm_name="$(.tart.vm.name)"
	$(.tart.cmd.rm-runtime-one)

rm-role-disks: $(.tart.vm.names.rm-role-disks-targets) ## Remove role disks for each name in .tart.vm.names (non-interactive)

%~rm-role-disks: FORCE
	vm_name="$${@%~rm-role-disks}"
	$(.tart.cmd.rm-role-disks-one)

rm-role-disks-one: ## Internal: remove role disks for .tart.vm.name (non-interactive)
	vm_name="$(.tart.vm.name)"
	$(.tart.cmd.rm-role-disks-one)

rm-owned-role-disks: ## Remove only owned role disk images resolved by .tart.disk.role.paths.effective
	$(.tart.cmd.rm-owned-role-disks)

rm: ## Remove runtime/artifact for .tart.rm.vm.name; remove only owned role disks unless .skip includes 'disks'
	$(MAKE) rm-runtime-one .tart.vm.name="$(.tart.rm.vm.name)"
	if [[ " $(.skip) " == *" disks "* ]]; then
		: "Skipping role disk removal because .skip includes 'disks'."
		: "VM $(.tart.rm.vm.name): removed runtime/artifact; skipped owned role disks (.skip includes 'disks')."
	elif [[ "$(.tart.run.extra-disks.add-renamed)" == "1" && "$(.rm.skip-owned-disks-when-add-renamed)" == "1" ]]; then
		: "Skipping role disk removal because renamed-disk mode is enabled (.tart.run.extra-disks.add-renamed=1)."
		: "Set .rm.skip-owned-disks-when-add-renamed=0 to allow owned-role-disk deletion explicitly."
		: "VM $(.tart.rm.vm.name): removed runtime/artifact; preserved owned role disks by safety guard."
	else
		$(MAKE) rm-owned-role-disks .tart.vm.name="$(.tart.rm.vm.name)"
		: "VM $(.tart.rm.vm.name): removed runtime/artifact and owned role disks only."
	fi

refresh-console: rm build console ## Fresh credential-debug flow: wipe VM+disks, rebuild, launch with console

refresh: validate-tart $(.env.file) ## Rebuild from existing VM into candidate VM (.tart.update.from-vm -> .tart.update.to-vm)
	if [[ "$(.tart.update.from-vm)" == "$(.tart.update.to-vm)" && "$(.tart.update.tart-home)" == "$(.tart.home)" ]]; then
		echo "Refusing refresh with identical source/target VM names." >&2
		echo "Use a distinct .tart.update.to-vm (e.g. nikopol-refresh) or a dedicated .tart.update.tart-home." >&2
		exit 2
	fi
	$(call .env.load)
	if ! $(.tart.cmd) get "$(.tart.update.from-vm)" >/dev/null 2>&1; then
		echo "Missing source VM to refresh from: $(.tart.update.from-vm)" >&2
		exit 2
	fi
	source_vm_state="$$( $(.tart.cmd) list | awk -v vm="$(.tart.update.from-vm)" '$$1=="local" && $$2==vm {print $$NF; found=1; exit} END { if (!found) print "" }' )"
	if [[ "$$source_vm_state" == "running" ]]; then
		echo "Refusing refresh while source VM is running: $(.tart.update.from-vm)" >&2
		echo "Stop it first (e.g. tart stop $(.tart.update.from-vm))." >&2
		exit 2
	fi
	base_ref="$(.tart.update.from-vm)"
	if [[ "$(.tart.update.tart-home)" != "$(.tart.home)" && "$(.tart.update.link-source-vm)" == "1" ]]; then
		refresh_vms_dir="$(.tart.update.tart-home)/vms"
		mkdir -p "$$refresh_vms_dir"
		src_vm_dir="$(.tart.home)/vms/$(.tart.update.from-vm)"
		if [[ ! -e "$$src_vm_dir" ]]; then
			echo "Missing source VM directory for symlink: $$src_vm_dir" >&2
			exit 2
		fi
		alias_path="$$refresh_vms_dir/$(.tart.update.source-vm-alias)"
		if [[ "$(.dry-run.tart.effective)" == "1" ]]; then
			echo "DRY-RUN[tart]: would symlink source VM $$src_vm_dir -> $$alias_path"
		else
			ln -sfn "$$src_vm_dir" "$$alias_path"
		fi
		base_ref="$(.tart.update.source-vm-alias)"
	fi
	if [[ "$(.tart.update.link-role-disks)" == "1" ]]; then
		dst_dir="$(.tart.update.tart-home)/disks/$(.tart.update.to-vm)"
		mkdir -p "$$dst_dir"
		for base in user-data.asif user-library.asif git-bare-store.asif git-store.asif nix-store.asif build-chains-cache.asif vm-images.asif; do
			src="$(.tart.home)/disks/$(.tart.update.from-vm)/$$base"
			dst="$$dst_dir/$$base"
			if [[ -e "$$src" ]]; then
				if [[ "$$(readlink "$$dst" 2>/dev/null || true)" != "$$src" ]]; then
					if [[ "$(.dry-run.disk.effective)" == "1" ]]; then
						echo "DRY-RUN[disk]: would symlink $$src -> $$dst"
					else
						ln -sfn "$$src" "$$dst"
					fi
				fi
			fi
		done
	fi
	$(MAKE) build-image TART_HOME="$(.tart.update.tart-home)" .template="$(.template.customize)" .tart.base.ref="$$base_ref" .tart.vm.name="$(.tart.update.to-vm)" .tart.disk.source-vm="$(.tart.update.to-vm)" .provision.profile="$(.tart.update.profile)" .macos.relax-session-tweaks="$(.tart.update.relax-session-tweaks)"

promote: validate-tart $(.env.file) ## Replace .tart.update.from-vm with .tart.update.to-vm by clone promotion
	if [[ "$(.tart.update.from-vm)" == "$(.tart.update.to-vm)" ]]; then
		echo "Refusing promotion with identical source/target VM names." >&2
		exit 2
	fi
	source_home="$(.tart.update.tart-home)"
	target_home="$(.tart.home)"
	promote_source_name="$(.tart.update.to-vm)"
	import_name="$(.tart.update.source-vm-alias)-promote"
	import_path="$$target_home/vms/$$import_name"
	refresh_vm_dir="$$source_home/vms/$(.tart.update.to-vm)"
	if [[ "$(.dry-run.tart.effective)" == "1" ]]; then
		if [[ "$$source_home" != "$$target_home" ]]; then
			echo "DRY-RUN[tart]: would move refreshed VM $$refresh_vm_dir -> $$import_path"
			echo "DRY-RUN[tart]: would stop/delete $(.tart.update.from-vm) in $$target_home then clone $$import_name -> $(.tart.update.from-vm)"
			echo "DRY-RUN[tart]: would remove temporary imported VM $$import_path"
		else
			echo "DRY-RUN[tart]: would stop/delete $(.tart.update.from-vm) then clone $(.tart.update.to-vm) -> $(.tart.update.from-vm)"
		fi
		exit 0
	fi
	if ! TART_HOME="$$source_home" $(.tart.cmd) get "$(.tart.update.to-vm)" >/dev/null 2>&1; then
		echo "Missing refreshed VM to promote: $(.tart.update.to-vm)" >&2
		exit 2
	fi
	if [[ "$$source_home" != "$$target_home" ]]; then
		if [[ ! -e "$$refresh_vm_dir" ]]; then
			echo "Missing refreshed VM directory for promotion: $$refresh_vm_dir" >&2
			exit 2
		fi
		mkdir -p "$$target_home/vms"
		rm -rf "$$import_path"
		if ! mv "$$refresh_vm_dir" "$$import_path"; then
			echo "Failed to move refreshed VM for promotion: $$refresh_vm_dir -> $$import_path" >&2
			exit 2
		fi
		promote_source_name="$$import_name"
		cleanup_import() {
			rm -rf "$$import_path" >/dev/null 2>&1 || true
		}
		trap cleanup_import EXIT
	fi
	TART_HOME="$$target_home" $(.tart.cmd) stop "$(.tart.update.from-vm)" >/dev/null 2>&1 || true
	if TART_HOME="$$target_home" $(.tart.cmd) get "$(.tart.update.from-vm)" >/dev/null 2>&1; then
		TART_HOME="$$target_home" $(.tart.cmd) delete "$(.tart.update.from-vm)"
	fi
	TART_HOME="$$target_home" $(.tart.cmd) clone "$$promote_source_name" "$(.tart.update.from-vm)"
	if [[ "$$source_home" != "$$target_home" ]]; then
		cleanup_import
		trap - EXIT
	fi
	: "Promoted $(.tart.update.to-vm) -> $(.tart.update.from-vm)"

shell-fmt: ## Format shell scripts if shfmt is available
	if command -v shfmt >/dev/null 2>&1; then
		shfmt -w scripts/*.sh
	else
		: "shfmt not found, skipping."
	fi

shell-check: ## Lint shell scripts if shellcheck is available
	if command -v shellcheck >/dev/null 2>&1; then
		shellcheck scripts/*.sh
	else
		: "shellcheck not found, skipping."
	fi

fmt: shell-fmt ## Alias for shell-fmt

FORCE:
