#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
DSCL_HELPER_LIB="${SCRIPT_DIR}/lib/dscl-plist.sh"
if [[ -f "${DSCL_HELPER_LIB}" ]]; then
  # shellcheck disable=SC1091
  source "${DSCL_HELPER_LIB}"
fi
ENV_FILE="${SCRIPT_DIR}/.envrc"
if [[ ! -f "${ENV_FILE}" && -n "${MACOS_ENV_FILE:-}" ]]; then
  ENV_FILE="${MACOS_ENV_FILE}"
fi
if [[ -f "${ENV_FILE}" ]]; then
  # shellcheck disable=SC1090
  source "${ENV_FILE}"
fi

: "${MACOS_DEBUG_MODE:=1}"
if [[ "${MACOS_DEBUG_MODE}" == "1" ]]; then
  set -x
fi

: "${NIX_INSTALLER_URL:=https://artifacts.nixos.org/nix-installer}"
: "${NIX_INSTALLER_PATH:=/private/var/lib/bootstrap/nix/nix-installer}"
: "${NIX_INSTALL_AT_BUILD:=0}"
: "${NIX_INSTALL_ALLOW_UNMOUNTED_NIX:=1}"
: "${NIX_DEFER_INSTALL_ON_MOUNT_FAILURE:=1}"
: "${NIX_EXPECTED_VOLUME_LABEL:=Nix Store}"
: "${NIX_EXPECTED_VOLUME_LABEL:=${DATA_DISK_NIX_STORE_NAME:-Nix Store}}"
: "${NIX_REQUIRE_EXISTING_STORE_VOLUME:=1}"
: "${NIX_STORE_CONFIGURE_SYSTEM_MOUNT:=1}"
: "${NIX_STORE_SYSTEM_MOUNT_POINT:=/nix}"
: "${NIX_STORE_CONFIGURE_SYNTHETIC:=1}"
: "${NIX_STORE_CONFIGURE_FSTAB:=1}"
: "${NIX_STORE_FSTAB_MOUNT_OPTS:=rw,noauto,nobrowse,nosuid,noatime,owners}"
: "${FLOX_INSTALL_WITH_NIX:=1}"
: "${FLOX_INSTALL_REF:=github:flox/flox}"
: "${NIX_DARWIN_INSTALL_WITH_NIX:=1}"
: "${NIX_DARWIN_INSTALL_REF:=github:nix-darwin/nix-darwin}"
: "${NIX_BOOTSTRAP_USER:=${DATA_HOME_USER:-${PRIMARY_ACCOUNT_NAME:-}}}"
: "${SECONDARY_ADMIN_NAME:=super}"
: "${NIX_TRUSTED_USERS:=root ${SECONDARY_ADMIN_NAME} ${PRIMARY_ACCOUNT_NAME:-nxmatic}}"
: "${NIX_BOOTSTRAP_SBIN_REL_PATH:=/opt/tart/sbin}"

normalize_trusted_users() {
  local current_users="$1"
  local secondary_user="$2"
  local primary_user="$3"

  printf '%s\n' "root ${secondary_user} ${primary_user} ${current_users}" \
    | tr ' ' '\n' \
    | awk 'NF && !seen[$0]++ { out = out (out ? " " : "") $0 } END { print out }'
}

NIX_TRUSTED_USERS="$(normalize_trusted_users "${NIX_TRUSTED_USERS}" "${SECONDARY_ADMIN_NAME:-super}" "${PRIMARY_ACCOUNT_NAME:-nxmatic}")"

resolve_home_dir_for_user() {
  local user="$1"
  if declare -F dscl_user_home_dir >/dev/null 2>&1; then
    dscl_user_home_dir "${user}"
  else
    echo "/Users/${user}"
  fi
}

NIX_BOOTSTRAP_HOME="$(resolve_home_dir_for_user "${NIX_BOOTSTRAP_USER}")"
if [[ "${NIX_BOOTSTRAP_USER}" != "admin" && "${NIX_BOOTSTRAP_HOME}" == "/Users/admin" ]]; then
  echo "Warning: Nix bootstrap home resolved to /Users/admin; using canonical /Users/${NIX_BOOTSTRAP_USER} for helper install target."
  NIX_BOOTSTRAP_HOME="/Users/${NIX_BOOTSTRAP_USER}"
fi

if [[ "${NIX_BOOTSTRAP_SBIN_REL_PATH}" == /* ]]; then
  : "${NIX_BOOTSTRAP_SBIN_DIR:=${NIX_BOOTSTRAP_SBIN_REL_PATH}}"
else
  : "${NIX_BOOTSTRAP_SBIN_DIR:=${NIX_BOOTSTRAP_HOME}/${NIX_BOOTSTRAP_SBIN_REL_PATH}}"
fi
: "${NIX_INSTALLER_PATH:=${NIX_BOOTSTRAP_SBIN_DIR}/nix-installer}"
: "${NIX_BOOTSTRAP_SCRIPT_PATH:=${NIX_BOOTSTRAP_SBIN_DIR}/install-nix-bootstrap}"
: "${NIX_BOOTSTRAP_ENV_PATH:=${NIX_BOOTSTRAP_SBIN_DIR}/install-nix-bootstrap.env}"

NIX_MOUNT_RECOVERY_DEFERRED=0

stage_nix_bootstrap_assets() {
  local tmp_env

  sudo mkdir -p "${NIX_BOOTSTRAP_SBIN_DIR}"
  sudo install -m 0755 "$0" "${NIX_BOOTSTRAP_SCRIPT_PATH}"
  sudo chown "${NIX_BOOTSTRAP_USER}:staff" "${NIX_BOOTSTRAP_SCRIPT_PATH}" >/dev/null 2>&1 || true

  tmp_env="$(mktemp)"
  {
    printf '%s\n' '# Generated by install-nix-installer.sh for deferred/full bootstrap reruns.'
    printf 'NIX_INSTALLER_URL=%q\n' "${NIX_INSTALLER_URL}"
    printf 'NIX_INSTALLER_PATH=%q\n' "${NIX_INSTALLER_PATH}"
    printf 'NIX_INSTALL_AT_BUILD=%q\n' "${NIX_INSTALL_AT_BUILD}"
    printf 'NIX_INSTALL_ALLOW_UNMOUNTED_NIX=%q\n' "${NIX_INSTALL_ALLOW_UNMOUNTED_NIX}"
    printf 'NIX_DEFER_INSTALL_ON_MOUNT_FAILURE=%q\n' "${NIX_DEFER_INSTALL_ON_MOUNT_FAILURE}"
    printf 'NIX_EXPECTED_VOLUME_LABEL=%q\n' "${NIX_EXPECTED_VOLUME_LABEL}"
    printf 'NIX_REQUIRE_EXISTING_STORE_VOLUME=%q\n' "${NIX_REQUIRE_EXISTING_STORE_VOLUME}"
    printf 'NIX_STORE_CONFIGURE_SYSTEM_MOUNT=%q\n' "${NIX_STORE_CONFIGURE_SYSTEM_MOUNT}"
    printf 'NIX_STORE_SYSTEM_MOUNT_POINT=%q\n' "${NIX_STORE_SYSTEM_MOUNT_POINT}"
    printf 'NIX_STORE_CONFIGURE_SYNTHETIC=%q\n' "${NIX_STORE_CONFIGURE_SYNTHETIC}"
    printf 'NIX_STORE_CONFIGURE_FSTAB=%q\n' "${NIX_STORE_CONFIGURE_FSTAB}"
    printf 'NIX_STORE_FSTAB_MOUNT_OPTS=%q\n' "${NIX_STORE_FSTAB_MOUNT_OPTS}"
    printf 'FLOX_INSTALL_WITH_NIX=%q\n' "${FLOX_INSTALL_WITH_NIX}"
    printf 'FLOX_INSTALL_REF=%q\n' "${FLOX_INSTALL_REF}"
    printf 'NIX_DARWIN_INSTALL_WITH_NIX=%q\n' "${NIX_DARWIN_INSTALL_WITH_NIX}"
    printf 'NIX_DARWIN_INSTALL_REF=%q\n' "${NIX_DARWIN_INSTALL_REF}"
    printf 'NIX_BOOTSTRAP_USER=%q\n' "${NIX_BOOTSTRAP_USER}"
    printf 'NIX_TRUSTED_USERS=%q\n' "${NIX_TRUSTED_USERS}"
  } > "${tmp_env}"

  sudo install -m 0600 "${tmp_env}" "${NIX_BOOTSTRAP_ENV_PATH}"
  sudo chown "${NIX_BOOTSTRAP_USER}:staff" "${NIX_BOOTSTRAP_ENV_PATH}" >/dev/null 2>&1 || true
  rm -f "${tmp_env}"
}

print_deferred_bootstrap_command() {
  echo "Run after reboot (full Nix/Flox bootstrap):"
  echo "  sudo env MACOS_ENV_FILE='${NIX_BOOTSTRAP_ENV_PATH}' bash -x '${NIX_BOOTSTRAP_SCRIPT_PATH}'"
}

stage_nix_bootstrap_assets

: "Fetch modern Nix installer"
INSTALLER_TMP="$(mktemp)"
trap 'rm -f "${INSTALLER_TMP}"' EXIT

if [[ ! "${NIX_INSTALLER_URL}" =~ ^https?:// ]]; then
  echo "Error: NIX_INSTALLER_URL must be an absolute http(s) URL, got '${NIX_INSTALLER_URL}'." >&2
  exit 1
fi

sudo mkdir -p "$(dirname "${NIX_INSTALLER_PATH}")"
curl -fsSL "${NIX_INSTALLER_URL}" -o "${INSTALLER_TMP}"
sudo install -m 0755 "${INSTALLER_TMP}" "${NIX_INSTALLER_PATH}"
sudo chown "${NIX_BOOTSTRAP_USER}:staff" "${NIX_INSTALLER_PATH}" >/dev/null 2>&1 || true

if [[ "${NIX_INSTALL_AT_BUILD}" != "1" ]]; then
  echo "Nix installer staged at ${NIX_INSTALLER_PATH}."
  echo "Bootstrap script staged at ${NIX_BOOTSTRAP_SCRIPT_PATH}."
  echo "Bootstrap env staged at ${NIX_BOOTSTRAP_ENV_PATH}."
  echo "Deferred install mode (NIX_INSTALL_AT_BUILD=${NIX_INSTALL_AT_BUILD})."
  print_deferred_bootstrap_command
  if [[ "${FLOX_INSTALL_WITH_NIX}" == "1" ]]; then
    echo "Flox install deferred and included in the full bootstrap rerun."
  fi
  if [[ "${NIX_DARWIN_INSTALL_WITH_NIX}" == "1" ]]; then
    echo "nix-darwin install deferred and included in the full bootstrap rerun."
  fi
  exit 0
fi

if ! mount | awk -v m=" on ${NIX_STORE_SYSTEM_MOUNT_POINT} " 'index($0, m) { found=1 } END { exit !found }'; then
  echo "Info: ${NIX_STORE_SYSTEM_MOUNT_POINT} is not currently mounted; delegating mount/bootstrap handling to the Nix installer."
fi

device_identifier_for_ref() {
  local ref="$1"
  local dev=""

  dev="$(diskutil info -plist "${ref}" | plutil -extract DeviceIdentifier raw -o - - 2>/dev/null || true)"
  if [[ -n "${dev}" ]]; then
    echo "${dev}"
    return 0
  fi

  # Fallback for APFS label lookups that can fail via `diskutil info <label>`
  # during certain provisioning/reconnect phases.
  dev="$(diskutil apfs list 2>/dev/null | awk -v label="${ref}" '
    {
      if (match($0, /Volume disk[0-9]+s[0-9]+/)) {
        current = substr($0, RSTART + 7, RLENGTH - 7)
      }
      if ($0 ~ /Name:[[:space:]]+/) {
        name = $0
        sub(/^.*Name:[[:space:]]*/, "", name)
        sub(/[[:space:]]+\(Case-insensitive\).*$/, "", name)
        if (tolower(name) == tolower(label) && current != "") {
          print current
          exit
        }
      }
    }
  ' || true)"

  if [[ -n "${dev}" ]]; then
    echo "${dev}"
  fi
}

volume_label_exists() {
  local label="$1"
  local dev=""

  dev="$(device_identifier_for_ref "${label}")"
  [[ -n "${dev}" ]]
}

volume_uuid_for_ref() {
  local ref="$1"
  local uuid=""
  local dev=""

  uuid="$(diskutil info -plist "${ref}" | plutil -extract VolumeUUID raw -o - - 2>/dev/null || true)"
  if [[ -n "${uuid}" ]]; then
    echo "${uuid}"
    return 0
  fi

  dev="$(device_identifier_for_ref "${ref}")"
  if [[ -n "${dev}" ]]; then
    uuid="$(diskutil info -plist "/dev/${dev}" | plutil -extract VolumeUUID raw -o - - 2>/dev/null || true)"
  fi

  if [[ -n "${uuid}" ]]; then
    echo "${uuid}"
  fi
}

ensure_nix_fstab_entry() {
  local vol_label="$1"
  local fstab_file="/etc/fstab"
  local vol_uuid=""
  local entry=""
  local tmp_file

  if [[ "${NIX_STORE_CONFIGURE_FSTAB}" != "1" ]]; then
    echo "Info: skipping /etc/fstab management for ${NIX_STORE_SYSTEM_MOUNT_POINT} because NIX_STORE_CONFIGURE_FSTAB=${NIX_STORE_CONFIGURE_FSTAB}."
    return 0
  fi

  vol_uuid="$(volume_uuid_for_ref "${vol_label}")"
  if [[ -z "${vol_uuid}" ]]; then
    echo "Warning: unable to resolve VolumeUUID for '${vol_label}'; cannot enforce /etc/fstab entry for ${NIX_STORE_SYSTEM_MOUNT_POINT}." >&2
    return 1
  fi

  entry="UUID=${vol_uuid} ${NIX_STORE_SYSTEM_MOUNT_POINT} apfs ${NIX_STORE_FSTAB_MOUNT_OPTS}"

  sudo touch "${fstab_file}"

  if sudo grep -Fqx "${entry}" "${fstab_file}"; then
    echo "Confirmed ${fstab_file} entry for ${NIX_STORE_SYSTEM_MOUNT_POINT}: ${entry}"
    return 0
  fi

  echo "Ensuring ${fstab_file} entry for ${NIX_STORE_SYSTEM_MOUNT_POINT} (${vol_label}, UUID=${vol_uuid})."
  tmp_file="$(mktemp)"
  sudo awk -v mp="${NIX_STORE_SYSTEM_MOUNT_POINT}" '
    NF == 0 { print; next }
    $0 ~ /^[[:space:]]*#/ { print; next }
    $2 == mp { next }
    { print }
  ' "${fstab_file}" > "${tmp_file}"
  printf '%s\n' "${entry}" | sudo tee -a "${tmp_file}" >/dev/null
  sudo mv "${tmp_file}" "${fstab_file}"
  sudo chmod 0644 "${fstab_file}"
  return 0
}

detect_nix_mount() {
  local mount_line=""
  local synthetic_target="/System/Volumes/Data${NIX_STORE_SYSTEM_MOUNT_POINT}"

  mount_line="$(mount | awk -v m1=" on ${NIX_STORE_SYSTEM_MOUNT_POINT} " -v m2=" on ${synthetic_target} " 'index($0, m1) || index($0, m2) { print; exit }' || true)"
  if [[ -z "${mount_line}" ]]; then
    return 1
  fi

  # Example: /dev/disk13s1 on /System/Volumes/Data/nix (apfs, local, ...)
  # shellcheck disable=SC2001
  echo "${mount_line}" | sed -E 's#^(/dev/[^[:space:]]+) on ([^[:space:]]+) .*#\1 \2#'
}

verify_nix_mount_matches_expected() {
  local vol_label="$1"
  local require_existing="$2"
  local expected_dev=""
  local detected=""
  local mounted_path=""
  local mounted_dev=""

  detected="$(detect_nix_mount || true)"
  if [[ -z "${detected}" ]]; then
    return 1
  fi

  mounted_dev="$(awk '{print $1}' <<<"${detected}" | sed 's#^/dev/##')"
  mounted_path="$(awk '{print $2}' <<<"${detected}")"

  expected_dev="$(device_identifier_for_ref "${vol_label}")"

  if [[ "${require_existing}" == "1" && "${mounted_path}" != "${NIX_STORE_SYSTEM_MOUNT_POINT}" ]]; then
    echo "Error: expected canonical ${NIX_STORE_SYSTEM_MOUNT_POINT} mountpoint, but detected '${mounted_path}'." >&2
    return 2
  fi

  if [[ "${require_existing}" == "1" && -n "${expected_dev}" && "${mounted_dev}" != "${expected_dev}" ]]; then
    echo "Error: Nix mountpoint (${mounted_path}) is mounted from '${mounted_dev:-unknown}', expected '${expected_dev}' (${vol_label})." >&2
    return 2
  fi

  echo "Confirmed Nix mountpoint (${mounted_path}) is mounted from expected/allowed volume (${vol_label}, ${mounted_dev:-unknown})."
  return 0
}

ensure_synthetic_nix_anchor() {
  local synthetic_conf="/etc/synthetic.conf"
  local synthetic_dir_entry="nix"
  local synthetic_symlink_entry=$'nix\tSystem/Volumes/Data/nix'
  local tmp_file

  sudo touch "${synthetic_conf}"

  if sudo grep -Fqx "${synthetic_symlink_entry}" "${synthetic_conf}"; then
    echo "Replacing legacy synthetic /nix symlink entry with canonical synthetic directory entry in ${synthetic_conf}."
    tmp_file="$(mktemp)"
    sudo awk -v bad="${synthetic_symlink_entry}" '$0 != bad { print }' "${synthetic_conf}" > "${tmp_file}"
    sudo mv "${tmp_file}" "${synthetic_conf}"
  fi

  if ! sudo grep -Fxq "${synthetic_dir_entry}" "${synthetic_conf}"; then
    echo "Ensuring canonical synthetic /nix directory entry in ${synthetic_conf}."
    printf '%s\n' "${synthetic_dir_entry}" | sudo tee -a "${synthetic_conf}" >/dev/null
  fi
}

attempt_direct_nix_mount_from_expected_volume() {
  local vol_label="$1"
  local require_existing="$2"
  local expected_dev=""
  local mount_target="${NIX_STORE_SYSTEM_MOUNT_POINT}"
  local apfs_boot_util_bin="/System/Library/Filesystems/apfs.fs/Contents/Resources/apfs_boot_util"

  expected_dev="$(device_identifier_for_ref "${vol_label}")"
  if [[ -z "${expected_dev}" ]]; then
    echo "Warning: unable to resolve expected device for volume '${vol_label}' during direct ${NIX_STORE_SYSTEM_MOUNT_POINT} mount attempt."
    return 1
  fi

  if [[ ! -e "${NIX_STORE_SYSTEM_MOUNT_POINT}" ]]; then
    if ! sudo mkdir -p "${NIX_STORE_SYSTEM_MOUNT_POINT}" >/dev/null 2>&1; then
      if [[ "${require_existing}" == "1" ]]; then
        echo "Warning: strict mode requires canonical ${NIX_STORE_SYSTEM_MOUNT_POINT} mountpoint from dedicated volume, but it is not creatable in this boot."
        return 1
      fi

      if [[ "${NIX_STORE_CONFIGURE_SYNTHETIC}" != "1" || "${NIX_STORE_SYSTEM_MOUNT_POINT}" != "/nix" ]]; then
        echo "Warning: synthetic fallback disabled or unsupported for mountpoint ${NIX_STORE_SYSTEM_MOUNT_POINT}; cannot realize mountpoint in this boot."
        return 1
      fi

      echo "Info: ${NIX_STORE_SYSTEM_MOUNT_POINT} cannot be created directly (likely read-only root); using synthetic Data anchor fallback."
      ensure_synthetic_nix_anchor
      mount_target="/System/Volumes/Data/nix"
      if [[ -x "${apfs_boot_util_bin}" ]]; then
        sudo "${apfs_boot_util_bin}" 1 || true
        sudo "${apfs_boot_util_bin}" 2 || true
      fi
    fi
  fi

  if [[ "${mount_target}" == "${NIX_STORE_SYSTEM_MOUNT_POINT}" && ! -d "${NIX_STORE_SYSTEM_MOUNT_POINT}" ]]; then
    echo "Warning: ${NIX_STORE_SYSTEM_MOUNT_POINT} mountpoint is still unavailable."
    return 1
  fi

  if mount | awk -v m=" on ${NIX_STORE_SYSTEM_MOUNT_POINT} " 'index($0, m) { found=1 } END { exit !found }'; then
    return 0
  fi

  echo "Attempting direct mount of /dev/${expected_dev} at ${mount_target}..."
  sudo mount -t apfs "/dev/${expected_dev}" "${mount_target}" >/dev/null 2>&1 || true

  if mount | awk -v m=" on ${NIX_STORE_SYSTEM_MOUNT_POINT} " 'index($0, m) { found=1 } END { exit !found }'; then
    echo "Direct mount succeeded for /dev/${expected_dev} -> ${NIX_STORE_SYSTEM_MOUNT_POINT}."
    return 0
  fi

  if [[ "${mount_target}" != "${NIX_STORE_SYSTEM_MOUNT_POINT}" ]] && mount | awk -v m=" on ${mount_target} " 'index($0, m) { found=1 } END { exit !found }'; then
    echo "Info: volume mounted at ${mount_target}; re-running APFS boot phases to expose ${NIX_STORE_SYSTEM_MOUNT_POINT} synthetic path."
    if [[ -x "${apfs_boot_util_bin}" ]]; then
      sudo "${apfs_boot_util_bin}" 1 || true
      sudo "${apfs_boot_util_bin}" 2 || true
    fi
  fi

  if mount | awk -v m=" on ${NIX_STORE_SYSTEM_MOUNT_POINT} " 'index($0, m) { found=1 } END { exit !found }'; then
    echo "Synthetic ${NIX_STORE_SYSTEM_MOUNT_POINT} path became active after APFS boot phases."
    return 0
  fi

  echo "Warning: direct mount recovery did not produce ${NIX_STORE_SYSTEM_MOUNT_POINT} mountpoint for /dev/${expected_dev}."
  return 1
}

ensure_nix_mountpoint_uses_expected_volume() {
  local vol_label="$1"
  local require_existing="$2"
  local apfs_boot_util_bin="/System/Library/Filesystems/apfs.fs/Contents/Resources/apfs_boot_util"

  if verify_nix_mount_matches_expected "${vol_label}" "${require_existing}"; then
    return 0
  fi

  if [[ $? -eq 2 ]]; then
    exit 1
  fi

  if ! volume_label_exists "${vol_label}"; then
    if [[ "${require_existing}" == "1" ]]; then
      echo "Error: expected APFS volume '${vol_label}' not found; refusing to let installer create a duplicate store volume." >&2
      echo "       Set NIX_REQUIRE_EXISTING_STORE_VOLUME=0 to allow installer-managed volume creation." >&2
      exit 1
    fi
    return 0
  fi

  if ! ensure_nix_fstab_entry "${vol_label}"; then
    if [[ "${NIX_REQUIRE_EXISTING_STORE_VOLUME}" == "1" ]]; then
      echo "Warning: strict mode expects persistent mount plumbing, but /etc/fstab entry could not be enforced." >&2
    fi
  fi

  if [[ "${NIX_STORE_CONFIGURE_SYNTHETIC}" == "1" && "${NIX_STORE_SYSTEM_MOUNT_POINT}" == "/nix" ]]; then
    echo "Ensuring /etc/synthetic.conf contains canonical /nix entry."
    ensure_synthetic_nix_anchor
  else
    echo "Info: skipping /etc/synthetic.conf management (NIX_STORE_CONFIGURE_SYNTHETIC=${NIX_STORE_CONFIGURE_SYNTHETIC}, mountpoint=${NIX_STORE_SYSTEM_MOUNT_POINT})."
  fi

  if [[ -e "${NIX_STORE_SYSTEM_MOUNT_POINT}" ]]; then
    echo "Info: ${NIX_STORE_SYSTEM_MOUNT_POINT} path already exists; checking mount state before APFS boot phases."
  else
    echo "Info: ${NIX_STORE_SYSTEM_MOUNT_POINT} path does not exist yet; applying APFS boot phases to realize synthetic mountpoint."
  fi

  if [[ -x "${apfs_boot_util_bin}" ]]; then
    echo "Applying APFS boot mount phases to activate synthetic/fstab mounts for ${NIX_STORE_SYSTEM_MOUNT_POINT}."
    sudo "${apfs_boot_util_bin}" 1 || true
    sudo "${apfs_boot_util_bin}" 2 || true
  else
    echo "Warning: apfs_boot_util not found at ${apfs_boot_util_bin}."
  fi

  if ! verify_nix_mount_matches_expected "${vol_label}" "${require_existing}"; then
    attempt_direct_nix_mount_from_expected_volume "${vol_label}" "${require_existing}" || true
  fi

  if ! verify_nix_mount_matches_expected "${vol_label}" "${require_existing}"; then
    if [[ "${require_existing}" != "1" ]]; then
      echo "Info: ${NIX_STORE_SYSTEM_MOUNT_POINT} mountpoint not fully realized in this boot, but non-strict mode is enabled (NIX_REQUIRE_EXISTING_STORE_VOLUME=${require_existing}); continuing."
      return 0
    fi

    if [[ "${require_existing}" == "1" ]]; then
      if [[ "${NIX_INSTALL_ALLOW_UNMOUNTED_NIX}" == "1" ]]; then
        echo "Warning: expected volume '${vol_label}' exists but ${NIX_STORE_SYSTEM_MOUNT_POINT} is not correctly mounted after all mount attempts; continuing because NIX_INSTALL_ALLOW_UNMOUNTED_NIX=1." >&2
        return 0
      fi
      if [[ "${NIX_DEFER_INSTALL_ON_MOUNT_FAILURE}" == "1" ]]; then
        echo "Warning: unable to realize ${NIX_STORE_SYSTEM_MOUNT_POINT} mountpoint for '${vol_label}' in this boot; deferring Nix installation because NIX_DEFER_INSTALL_ON_MOUNT_FAILURE=1." >&2
        NIX_MOUNT_RECOVERY_DEFERRED=1
        return 0
      fi
      echo "Error: expected volume '${vol_label}' exists but ${NIX_STORE_SYSTEM_MOUNT_POINT} is not correctly mounted after apfs_boot_util phases; refusing installer run to avoid duplicate volume creation." >&2
    fi
    exit 1
  fi
}

if [[ "${NIX_STORE_CONFIGURE_SYSTEM_MOUNT}" == "1" ]]; then
  ensure_nix_mountpoint_uses_expected_volume "${NIX_EXPECTED_VOLUME_LABEL}" "${NIX_REQUIRE_EXISTING_STORE_VOLUME}"
else
  echo "Info: skipping pre-installer mount enforcement because NIX_STORE_CONFIGURE_SYSTEM_MOUNT=${NIX_STORE_CONFIGURE_SYSTEM_MOUNT}."
fi

if [[ "${NIX_MOUNT_RECOVERY_DEFERRED}" == "1" ]]; then
  echo "Nix installer staged at ${NIX_INSTALLER_PATH}."
  echo "Bootstrap script staged at ${NIX_BOOTSTRAP_SCRIPT_PATH}."
  echo "Bootstrap env staged at ${NIX_BOOTSTRAP_ENV_PATH}."
  echo "Deferred install mode due to unresolved ${NIX_STORE_SYSTEM_MOUNT_POINT} mountpoint in current boot."
  print_deferred_bootstrap_command
  exit 0
fi

: "Run modern Nix installer"
if [[ "${MACOS_DEBUG_MODE}" == "1" ]]; then
  sudo bash -x "${NIX_INSTALLER_PATH}" install macos --no-confirm --volume-label "${NIX_EXPECTED_VOLUME_LABEL}"
else
  sudo bash "${NIX_INSTALLER_PATH}" install macos --no-confirm --volume-label "${NIX_EXPECTED_VOLUME_LABEL}"
fi

if [[ "${NIX_STORE_CONFIGURE_SYSTEM_MOUNT}" == "1" ]]; then
  if ! verify_nix_mount_matches_expected "${NIX_EXPECTED_VOLUME_LABEL}" "${NIX_REQUIRE_EXISTING_STORE_VOLUME}"; then
    echo "Error: after installer run, ${NIX_STORE_SYSTEM_MOUNT_POINT} is not mounted from expected Nix store volume." >&2
    exit 1
  fi
fi

if [[ -r "${NIX_STORE_SYSTEM_MOUNT_POINT}/var/nix/profiles/default/etc/profile.d/nix-daemon.sh" ]]; then
  # shellcheck disable=SC1091
  . "${NIX_STORE_SYSTEM_MOUNT_POINT}/var/nix/profiles/default/etc/profile.d/nix-daemon.sh"
fi

ensure_nix_custom_conf_block() {
  local nix_conf_file="/etc/nix/nix.conf"
  local conf_file="/etc/nix/nix.custom.conf"
  local block_begin="# BEGIN macos-image-template nix custom"
  local block_end="# END macos-image-template nix custom"
  local tmp_file
  local include_line="include ${conf_file}"

  sudo install -d -m 0755 /etc/nix
  sudo touch "${nix_conf_file}"
  sudo touch "${conf_file}"

  tmp_file="$(mktemp)"
  sudo awk '
    $0 ~ /^[[:space:]]*!?[[:space:]]*include[[:space:]]+((\/etc\/nix\/)?nix\.custom\.conf)[[:space:]]*$/ { next }
    { print }
  ' "${nix_conf_file}" | cat > "${tmp_file}"
  printf '%s\n' "${include_line}" | sudo tee -a "${tmp_file}" >/dev/null
  sudo mv "${tmp_file}" "${nix_conf_file}"

  if sudo grep -Fq "${block_begin}" "${conf_file}"; then
    tmp_file="$(mktemp)"
    sudo awk -v begin="${block_begin}" -v end="${block_end}" '
      $0 == begin { skip = 1; next }
      $0 == end   { skip = 0; next }
      skip != 1   { print }
    ' "${conf_file}" | cat > "${tmp_file}"
    sudo mv "${tmp_file}" "${conf_file}"
  fi

  {
    printf '%s\n' "${block_begin}"
    printf '%s\n' 'accept-flake-config = true'
    printf '%s\n' "trusted-users = ${NIX_TRUSTED_USERS}"
    printf '%s\n' 'extra-trusted-substituters = https://cache.flox.dev'
    printf '%s\n' 'extra-trusted-public-keys = flox-cache-public-1:7F4OyH7ZCnFhcze3fJdfyXYLQw/aV7GEed86nQ7IsOs='
    printf '%s\n' "${block_end}"
  } | sudo tee -a "${conf_file}" >/dev/null
}

ensure_nix_custom_conf_block

NIX_PROFILE_USER="${NIX_BOOTSTRAP_USER}"
if [[ -z "${NIX_PROFILE_USER}" ]]; then
  NIX_PROFILE_USER="$(id -un)"
fi
NIX_PROFILE_HOME="$(resolve_home_dir_for_user "${NIX_PROFILE_USER}")"

NIX_BIN=""
for candidate in \
  "${NIX_STORE_SYSTEM_MOUNT_POINT}/var/nix/profiles/default/bin/nix" \
  "${NIX_PROFILE_HOME}/.nix-profile/bin/nix" \
  "${HOME}/.nix-profile/bin/nix" \
  "$(command -v nix 2>/dev/null || true)"; do
  if [[ -n "${candidate}" && -x "${candidate}" ]]; then
    NIX_BIN="${candidate}"
    break
  fi
done

if [[ -z "${NIX_BIN}" ]]; then
  echo "Warning: Nix binary not found after install; skipping package bootstrap (git/flox/nix-darwin)."
  exit 0
fi

ensure_profile_user_writable_state() {
  local user="$1"
  local home="$2"
  local path

  for path in "${home}/.cache" "${home}/.cache/nix" "${home}/.local/state/nix"; do
    sudo mkdir -p "${path}"
    sudo chown -R "${user}:staff" "${path}" >/dev/null 2>&1 || true
    sudo chmod -R u+rwX "${path}" >/dev/null 2>&1 || true
  done
}

ensure_profile_user_writable_state "${NIX_PROFILE_USER}" "${NIX_PROFILE_HOME}"

run_nix_profile_add() {
  local pkg_ref="$1"
  local nix_cmd=("${NIX_BIN}" profile add --accept-flake-config "${pkg_ref}")

  if [[ "$(id -u)" -eq 0 && "${NIX_PROFILE_USER}" != "root" ]]; then
    nix_cmd=(sudo -u "${NIX_PROFILE_USER}" -H env "HOME=${NIX_PROFILE_HOME}" "${nix_cmd[@]}")
  fi
  "${nix_cmd[@]}"
}

target_command_exists() {
  local cmd="$1"

  if [[ "$(id -u)" -eq 0 && "${NIX_PROFILE_USER}" != "root" ]]; then
    sudo -u "${NIX_PROFILE_USER}" -H env HOME="${NIX_PROFILE_HOME}" bash -lc "command -v ${cmd} >/dev/null 2>&1"
  else
    command -v "${cmd}" >/dev/null 2>&1
  fi
}

: "Install git via Nix profile first (required for git-based flakes/inputs)"
if [[ -x "${NIX_STORE_SYSTEM_MOUNT_POINT}/var/nix/profiles/default/bin/git" ]] || [[ -x "${NIX_PROFILE_HOME}/.nix-profile/bin/git" ]]; then
  echo "Git already available; skipping install."
else
  run_nix_profile_add "nixpkgs#git"
fi

if [[ "${FLOX_INSTALL_WITH_NIX}" == "1" ]]; then
  : "Install Flox via Nix profile (idempotent)"
  if target_command_exists flox || [[ -x "${NIX_STORE_SYSTEM_MOUNT_POINT}/var/nix/profiles/default/bin/flox" ]] || [[ -x "${NIX_PROFILE_HOME}/.nix-profile/bin/flox" ]]; then
    echo "Flox already available; skipping install."
  else
    run_nix_profile_add "${FLOX_INSTALL_REF}"
  fi
fi

if [[ "${NIX_DARWIN_INSTALL_WITH_NIX}" == "1" ]]; then
  : "Install nix-darwin via Nix profile (idempotent)"
  if target_command_exists darwin-rebuild || [[ -x "${NIX_STORE_SYSTEM_MOUNT_POINT}/var/nix/profiles/default/bin/darwin-rebuild" ]] || [[ -x "${NIX_PROFILE_HOME}/.nix-profile/bin/darwin-rebuild" ]]; then
    echo "nix-darwin already available (darwin-rebuild found); skipping install."
  else
    run_nix_profile_add "${NIX_DARWIN_INSTALL_REF}"
  fi
fi
